{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "wec.xx.domain.com",
    "event_src.hostname": "wec",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.domain": "xxdomain",
    "object.account.id": "synthetic:wec$@xxdomain",
    "object.account.name": "wec$",
    "object.account.session_id": "999",
    "object.process.cmdline": "cmd.exe /c winrm get winrm/config/winrs >C:\\Windows\\TEMP\\2f8d8f32457d622bce40de0f199cd4cab74bd439.stdout 2>C:\\Windows\\TEMP\\2f8d8f32457d622bce40de0f199cd4cab74bd439.stderr & echo %ERRORLEVEL% >C:\\Windows\\TEMP\\2f8d8f32457d622bce40de0f199cd4cab74bd439.errorlevel",
    "object.process.fullpath": "c:\\windows\\system32\\cmd.exe",
    "object.process.id": "6516",
    "object.process.name": "cmd.exe",
    "object.process.parent.fullpath": "c:\\windows\\system32\\wbem\\wmiprvse.exe",
    "object.process.parent.id": "4416",
    "object.process.parent.name": "wmiprvse.exe",
    "object.process.parent.path": "c:\\windows\\system32\\wbem\\",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "xxdomain",
    "subject.account.id": "S-1-5-20",
    "subject.account.name": "wec$",
    "subject.account.privileges": "TokenElevationTypeDefault",
    "subject.account.session_id": "996",
    "subject.state": "on behalf of oneself",
    "time": "2021-09-08T06:06:18.245Z"
}
