{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.domain": "acme",
    "object.account.id": "S-1-5-18",
    "object.account.name": "someone$",
    "object.account.session_id": "999",
    "object.process.fullpath": "c:\\windows\\system32\\searchfilterhost.exe",
    "object.process.id": "8892",
    "object.process.name": "searchfilterhost.exe",
    "object.process.parent.id": "1384",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "acme",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "someone$",
    "subject.account.privileges": "TokenElevationTypeDefault",
    "subject.account.session_id": "999",
    "subject.state": "on behalf of oneself",
    "time": "2013-10-23T10:11:57.976Z"
}
