{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "as1-zxc-44.domain.com",
    "event_src.hostname": "as1-zxc-44",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.id": "S-1-5-18",
    "object.account.session_id": "999",
    "object.process.fullpath": "c:\\windows\\system32\\csrss.exe",
    "object.process.id": "584",
    "object.process.name": "csrss.exe",
    "object.process.parent.fullpath": "c:\\windows\\system32\\smss.exe",
    "object.process.parent.id": "576",
    "object.process.parent.name": "smss.exe",
    "object.process.parent.path": "c:\\windows\\system32\\",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.id": "S-1-5-18",
    "subject.account.privileges": "TokenElevationTypeDefault",
    "subject.account.session_id": "999",
    "subject.state": "nameless",
    "time": "2021-09-05T01:00:36.429Z"
}
