{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.domain": "server160",
    "object.account.id": "S-1-5-18",
    "object.account.name": "server16$",
    "object.account.session_id": "999",
    "object.process.cmdline": "C:\\Windows\\system32\\DllHost.exe /Processid:{E10F6C3A-F1AE-4ADC-AA9D-2FE65525666E}",
    "object.process.fullpath": "c:\\windows\\system32\\dllhost.exe",
    "object.process.id": "2028",
    "object.process.name": "dllhost.exe",
    "object.process.parent.fullpath": "c:\\windows\\system32\\svchost.exe",
    "object.process.parent.id": "808",
    "object.process.parent.name": "svchost.exe",
    "object.process.parent.path": "c:\\windows\\system32\\",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "server160",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "server16$",
    "subject.account.privileges": "TokenElevationTypeDefault",
    "subject.account.session_id": "999",
    "subject.state": "on behalf of oneself",
    "time": "2020-04-29T07:13:07.236Z"
}
