{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "ab6-ccc-ddd-78.example.com",
    "event_src.hostname": "ab6-ccc-ddd-78",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.domain": "virtual users",
    "object.account.id": "synthetic:sshd_16144@virtual users",
    "object.account.name": "sshd_16144",
    "object.account.session_id": "1086832012",
    "object.process.cmdline": "\"C:\\WINDOWS\\System32\\OpenSSH\\sshd.exe\" \"-y\"",
    "object.process.fullpath": "c:\\windows\\system32\\openssh\\sshd.exe",
    "object.process.id": "11592",
    "object.process.name": "sshd.exe",
    "object.process.parent.fullpath": "c:\\windows\\system32\\openssh\\sshd.exe",
    "object.process.parent.id": "16144",
    "object.process.parent.name": "sshd.exe",
    "object.process.parent.path": "c:\\windows\\system32\\openssh\\",
    "object.process.path": "c:\\windows\\system32\\openssh\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "example",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "ab6-ccc-ddd-78$",
    "subject.account.privileges": "TokenElevationTypeDefault",
    "subject.account.session_id": "999",
    "subject.state": "on behalf",
    "time": "2021-09-04T22:40:37.752Z"
}
