{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.hostname": "win-7tftfat5c5t",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4781_Name_of_account_changed",
    "importance": "info",
    "msgid": "4781",
    "object": "account",
    "object.account.domain": "builtin",
    "object.account.id": "S-1-5-32-556",
    "object.account.name": "network configuration operators",
    "object.new_value": "network configuration operators",
    "object.property": "name",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "workgroup",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "win-7tftfat5c5t$",
    "subject.account.session_id": "999",
    "time": "2015-05-29T18:34:09.942Z"
}
