{
    "action": "remove",
    "category.generic": "Registry Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_12_Registry_object_create_delete",
    "importance": "info",
    "msgid": "12",
    "object": "reg_object",
    "object.fullpath": "\\registry\\machine\\software\\microsoft\\windows nt\\currentversion\\schedule\\taskcache\\tree\\createexplorershellunelevatedtask",
    "object.name": "createexplorershellunelevatedtask",
    "object.path": "\\registry\\machine\\software\\microsoft\\windows nt\\currentversion\\schedule\\taskcache\\tree\\",
    "object.type": "registry key",
    "status": "success",
    "subject.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "subject.process.guid": "222467B7-74C6-5BEE-0000-00103C380100",
    "subject.process.id": "1100",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2018-11-19T12:28:25.653Z"
}
