{
    "action": "create",
    "category.generic": "Registry Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_12_Registry_object_create_delete",
    "importance": "info",
    "msgid": "12",
    "object": "reg_object",
    "object.fullpath": "\\registry\\machine\\system\\currentcontrolset\\services\\tcpip\\parameters",
    "object.name": "parameters",
    "object.path": "\\registry\\machine\\system\\currentcontrolset\\services\\tcpip\\",
    "object.type": "registry key",
    "status": "success",
    "subject.process.fullpath": "c:\\windows\\system32\\wbem\\wmiprvse.exe",
    "subject.process.guid": "222467B7-FDB8-5BF4-0000-00103CE22204",
    "subject.process.id": "2820",
    "subject.process.name": "wmiprvse.exe",
    "subject.process.path": "c:\\windows\\system32\\wbem\\",
    "time": "2018-11-21T07:56:48.299Z"
}
