{
    "action": "deny",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "44",
    "direction": "ingress",
    "dst.ip": "10.0.209.41",
    "dst.port": 137,
    "event_src.category": "Operating system",
    "event_src.hostname": "8p1x64-soft",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5157_WFP_blocked_a_connection",
    "importance": "info",
    "msgid": "5157",
    "object": "connection",
    "object.process.id": "4",
    "object.process.name": "System",
    "object.property": "ALE layer",
    "object.value": "Receive/Accept",
    "protocol": "17",
    "src.ip": "10.0.223.255",
    "src.port": 137,
    "status": "success",
    "subject": "rule",
    "subject.id": "65796",
    "time": "2015-12-30T11:01:25.667Z"
}
