{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "646",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_mgmt",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_MGMT",
    "object": "account",
    "object.account.id": "1001",
    "object.state": "pam_tally2",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.privileges": "0",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/sbin/pam_tally2",
    "subject.process.id": "2367",
    "subject.process.name": "pam_tally2",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-10-16T07:52:44.000Z"
}
