{
    "action": "start",
    "category.generic": "Executable Module",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_7_Image_loaded",
    "importance": "low",
    "msgid": "7",
    "object": "module",
    "object.process.fullpath": "c:\\windows\\syswow64\\rasadhlp.dll",
    "object.process.hash.sha256": "44FD17A3EC95EC7D0F568E132A6793BEB7582A8B48E7EEEC6C958BD217CFCA6A",
    "object.process.meta": "Description:Remote Access AutoDial Helper | Product:Microsoft® Windows® Operating System | Company:Microsoft Corporation",
    "object.process.name": "rasadhlp.dll",
    "object.process.original_name": "rasadhlp.dll",
    "object.process.path": "c:\\windows\\syswow64\\",
    "object.property": "signature status",
    "object.value": "Valid | Microsoft Windows",
    "object.version": "10.0.14393.0 (rs1_release.160715-1616)",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "c:\\mrunner\\23\\agent.23.0.2156\\modulerunner.exe",
    "subject.process.guid": "222467B7-8E00-5F75-0000-0010F415C304",
    "subject.process.id": "1788",
    "subject.process.name": "modulerunner.exe",
    "subject.process.path": "c:\\mrunner\\23\\agent.23.0.2156\\",
    "time": "2020-10-01T08:06:24.816Z"
}
