{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "16967031",
    "dst.hostname": "host",
    "event_src.category": "Operating system",
    "event_src.hostname": "host",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_login",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_service": "sshd",
    "msgid": "USER_LOGIN",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "37971",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "src.ip": "1.1.1.1",
    "status": "failure",
    "subject": "account",
    "subject.account.name": "(invalid user)",
    "time": "2022-05-31T15:09:59.000Z"
}
