{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "4380",
    "dst.ip": "192.168.137.192",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "remote",
    "logon_service": "sshd",
    "msgid": "USER_LOGIN",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "2396",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "src.ip": "192.168.137.1",
    "status": "failure",
    "subject": "account",
    "subject.account.name": "root",
    "time": "2019-12-09T05:18:01.000Z"
}
