{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "13696",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": "tty7",
    "msgid": "USER_LOGIN",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/lightdm",
    "object.process.id": "6072",
    "object.process.name": "lightdm",
    "object.process.path": "/usr/sbin/",
    "status": "failure",
    "subject": "account",
    "subject.account.name": "root",
    "time": "2019-12-10T13:27:55.000Z"
}
