{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "00000000-0000-0000-0000-000000000000",
    "datafield8": "DE8E9439-82BA-1479-2314-8A941F2A6D01",
    "dst.fqdn": "srv-sc-dpm1.ilp.loc",
    "dst.hostname": "srv-sc-dpm1",
    "event_src.category": "AAA",
    "event_src.fqdn": "srv-tsod-ex1.ilp.loc",
    "event_src.hostname": "srv-tsod-ex1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4648_A_logon_was_attempted_using_explicit_credentials",
    "importance": "medium",
    "msgid": "4648",
    "object": "system",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "ilp.loc",
    "subject.account.name": "srv-tsod-ex1$",
    "subject.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "subject.process.id": "788",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2016-05-26T13:00:11.511Z"
}
