{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "00000000-0000-0000-0000-000000000000",
    "datafield8": "43A4F2B3-938A-88B2-7601-F89281C04388",
    "event_src.category": "AAA",
    "event_src.fqdn": "srv-tsod-ex1.ilp.loc",
    "event_src.hostname": "srv-tsod-ex1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4648_A_logon_was_attempted_using_explicit_credentials",
    "importance": "medium",
    "msgid": "4648",
    "object": "system",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "ilp",
    "subject.account.name": "healthmailbox3053082",
    "subject.process.fullpath": "c:\\windows\\system32\\inetsrv\\w3wp.exe",
    "subject.process.id": "7020",
    "subject.process.name": "w3wp.exe",
    "subject.process.path": "c:\\windows\\system32\\inetsrv\\",
    "time": "2016-05-26T12:55:07.067Z"
}
