{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4724_An_attempt_was_made_to_reset_an_account_s_password",
    "importance": "medium",
    "msgid": "4724",
    "object": "account",
    "object.account.domain": "someone",
    "object.account.id": "S-1-5-21-3000000076-810000008-1900000808-1065",
    "object.account.name": "test",
    "object.property": "password",
    "reason": "An attempt was made to reset an accounts password",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "acme",
    "subject.account.id": "S-1-5-21-1000000030-700000027-3900000002-14342",
    "subject.account.name": "someone",
    "subject.account.session_id": "168660",
    "time": "2013-10-02T05:56:31.022Z"
}
