{
    "action": "logout",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "348",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_end",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": ":0",
    "msgid": "USER_END",
    "object": "system",
    "object.process.fullpath": "/usr/libexec/gdm-session-worker",
    "object.process.id": "1835",
    "object.process.name": "gdm-session-worker",
    "object.process.path": "/usr/libexec/",
    "status": "ongoing",
    "subject": "account",
    "subject.account.name": "gdm",
    "subject.state": "ended-session",
    "time": "2020-10-14T14:41:45.000Z"
}
