{
    "action": "logout",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "487",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_end",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": "cron",
    "msgid": "USER_END",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/crond",
    "object.process.id": "2266",
    "object.process.name": "crond",
    "object.process.path": "/usr/sbin/",
    "status": "success",
    "subject": "account",
    "subject.account.name": "root",
    "subject.account.session_id": "2",
    "subject.state": "ended-session",
    "time": "2020-10-16T07:50:01.000Z"
}
