{
    "action": "clean",
    "event_src.category": "Operating system",
    "event_src.hostname": "win-dge9hau611l",
    "event_src.subsys": "System",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_System_104_Log_was_cleared",
    "importance": "info",
    "msgid": "104",
    "object": "log",
    "object.name": "Application",
    "object.property": "backup path",
    "object.value": "\\\\WIN-DGE9HAU611L\\C$\\Users\\Administrator\\Desktop\\nomatter.evtx",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "win-dge9hau611l",
    "subject.account.id": "S-1-5-21-2887173632-2580675388-2225781737-500",
    "subject.account.name": "administrator",
    "time": "2017-08-10T07:58:33.965Z"
}
