{
    "action": "modify",
    "category.generic": "Registry Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_13_Registry_value_changed",
    "importance": "info",
    "msgid": "13",
    "object": "reg_object",
    "object.fullpath": "\\registry\\machine\\system\\currentcontrolset\\services\\tcpip\\parameters\\interfaces\\{c7c9928c-6985-4d07-9506-2f42aa3337be}\\dhcpipaddress",
    "object.name": "dhcpipaddress",
    "object.new_value": "192.168.236.133",
    "object.path": "\\registry\\machine\\system\\currentcontrolset\\services\\tcpip\\parameters\\interfaces\\{c7c9928c-6985-4d07-9506-2f42aa3337be}\\",
    "object.property": "value",
    "status": "success",
    "subject.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "subject.process.guid": "222467B7-74C5-5BEE-0000-0010551A0100",
    "subject.process.id": "944",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2018-11-19T12:27:01.439Z"
}
