{
    "action": "modify",
    "category.generic": "Registry Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "comp-5089.tube.stf",
    "event_src.hostname": "comp-5089",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_13_Registry_value_changed",
    "importance": "info",
    "msgid": "13",
    "object": "reg_object",
    "object.fullpath": "\\registry\\user\\s-1-5-21-215089694-3438683279-2836690124-1187\\control panel\\desktop\\transcodedimagecount",
    "object.name": "transcodedimagecount",
    "object.new_value": "dword (0x00000002)",
    "object.path": "\\registry\\user\\s-1-5-21-215089694-3438683279-2836690124-1187\\control panel\\desktop\\",
    "object.property": "value",
    "status": "success",
    "subject.account.domain": "tube",
    "subject.account.id": "synthetic:l_solomon@tube",
    "subject.account.name": "l_solomon",
    "subject.process.fullpath": "c:\\windows\\explorer.exe",
    "subject.process.guid": "e2abddde-13d5-637c-e10b-000000001a00",
    "subject.process.id": "9880",
    "subject.process.name": "explorer.exe",
    "subject.process.path": "c:\\windows\\",
    "time": "2022-11-23T23:59:56.246Z"
}
