{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "109",
    "datafield8": "5.1.18362.145",
    "event_src.category": "Operating system",
    "event_src.fqdn": "iivanov.domainname.ru",
    "event_src.hostname": "iivanov",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_pipeline_executed",
    "importance": "info",
    "msgid": "4103",
    "object": "command",
    "object.account.domain": "domainname",
    "object.account.id": "S-1-5-21-1023191730-727829927-3985050192-38786",
    "object.account.name": "iivanov",
    "object.process.cmdline": "\"Out-Default\" | \"Out-String\" -InputObject \"lasdfkjghdfkjgnm\"",
    "object.process.name": "Out-Default",
    "object.process.parent.cmdline": "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe",
    "object.process.parent.guid": "e2e8271a-668a-443f-b002-9ca100efdba7",
    "object.process.parent.id": "5316",
    "object.value": "CommandInvocation(Out-Default): \"Out-Default\"\r\nCommandInvocation(Out-String): \"Out-String\"\r\nParameterBinding(Out-Default): имя=\"InputObject\"; значение=\"lasdfkjghdfkjgnm\"",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "domainname",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-38786",
    "subject.account.name": "iivanov",
    "time": "2020-02-12T07:47:20.129Z"
}
