{
    "action": "create",
    "category.generic": "Service",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "computername.dnssuffix.ru",
    "event_src.hostname": "computername",
    "event_src.subsys": "System",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_7045_New_Windows_Service",
    "importance": "info",
    "msgid": "7045",
    "object": "service",
    "object.account.name": "localsystem",
    "object.name": "WindowsServiceVB",
    "object.process.cmdline": "C:\\Windows\\Temp\\WindowsServiceVB.exe",
    "object.property": "start type",
    "object.type": "user mode service",
    "object.value": "auto start",
    "status": "success",
    "subject": "account",
    "subject.account.id": "S-1-5-21-3228627042-334194140-788599944-1000",
    "time": "2017-09-22T10:04:15.263Z"
}
