{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "344",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "msgid": "USER_LOGIN",
    "object": "system",
    "object.process.fullpath": "/usr/libexec/gdm-session-worker",
    "object.process.id": "2130",
    "object.process.name": "gdm-session-worker",
    "object.process.path": "/usr/libexec/",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "1",
    "subject.state": "logged-in",
    "time": "2020-10-14T14:41:36.000Z"
}
