{
    "action": "bind",
    "event_src.category": "Other",
    "event_src.hostname": "blastfurnance",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_18_Pipe_connected",
    "importance": "info",
    "msgid": "18",
    "object": "resource",
    "object.name": "GSC_RT",
    "object.type": "pipe",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "blastfurnance",
    "subject.account.id": "synthetic:operator@blastfurnance",
    "subject.account.name": "operator",
    "subject.process.fullpath": "c:\\program files (x86)\\siemens\\wincc\\bin\\script.exe",
    "subject.process.guid": "298ea5b3-8d0c-6373-3801-000000005c00",
    "subject.process.id": "2848",
    "subject.process.name": "script.exe",
    "subject.process.path": "c:\\program files (x86)\\siemens\\wincc\\bin\\",
    "time": "2022-11-23T23:59:59.055Z"
}
