{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "campucter-home.company.ru",
    "event_src.hostname": "campucter-home",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_wmi_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.session_id": "0",
    "object.process.fullpath": "c:\\windows\\system32\\raserver.exe",
    "object.process.id": "11712",
    "object.process.name": "raserver.exe",
    "object.process.parent.fullpath": "c:\\windows\\system32\\svchost.exe",
    "object.process.parent.id": "2444",
    "object.process.parent.name": "svchost.exe",
    "object.process.parent.path": "c:\\windows\\system32\\",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "company",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "campucter-home$",
    "subject.account.privileges": "TokenElevationTypeDefault",
    "subject.account.session_id": "999",
    "subject.state": "on behalf of oneself",
    "time": "2017-08-10T10:47:14.000Z"
}
