{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "104979171",
    "dst.ip": "10.10.193.10",
    "event_src.category": "AAA",
    "event_src.ip": "10.10.193.10",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_acq",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "CRED_ACQ",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "3134601",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "reason": "PAM:setcred",
    "src.ip": "10.0.76.87",
    "status": "ongoing",
    "subject": "account",
    "subject.account.domain": "domain",
    "subject.account.id": "1702622305",
    "subject.account.name": "domuser",
    "subject.account.session_id": "6346",
    "subject.state": "acquired-credentials",
    "time": "2022-10-10T15:49:05.000Z"
}
