{
    "action": "start",
    "category.generic": "Thread",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "0x0000000000060000",
    "event_src.category": "Other",
    "event_src.fqdn": "comp-2159.hv-logistics.stf",
    "event_src.hostname": "comp-2159",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_8_Create_remote_thread",
    "importance": "low",
    "msgid": "8",
    "object": "thread",
    "object.account.domain": "hv-logistics",
    "object.account.id": "synthetic:d_jensen@hv-logistics",
    "object.account.name": "d_jensen",
    "object.fullpath": "-",
    "object.id": "23912",
    "object.name": "-",
    "object.process.fullpath": "c:\\windows\\system32\\rundll32.exe",
    "object.process.guid": "076CA06C-3B1D-637E-D023-000000003100",
    "object.process.id": "23804",
    "object.process.name": "rundll32.exe",
    "object.process.path": "c:\\windows\\system32\\",
    "object.property": "start function",
    "object.value": "-",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "hv-logistics",
    "subject.account.id": "synthetic:d_jensen@hv-logistics",
    "subject.account.name": "d_jensen",
    "subject.process.fullpath": "c:\\windows\\syswow64\\rundll32.exe",
    "subject.process.guid": "076CA06C-D262-637D-961C-000000003100",
    "subject.process.id": "4856",
    "subject.process.name": "rundll32.exe",
    "subject.process.path": "c:\\windows\\syswow64\\",
    "time": "2022-11-23T15:24:13.366Z"
}
