{
    "action": "start",
    "category.generic": "Thread",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "0x00000000000F0434",
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_8_Create_remote_thread",
    "importance": "low",
    "msgid": "8",
    "object": "thread",
    "object.id": "69612",
    "object.process.fullpath": "c:\\windows\\system32\\lsass.exe",
    "object.process.guid": "684DA293-FB38-5A2C-0000-0010FAA90000",
    "object.process.id": "608",
    "object.process.name": "lsass.exe",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "c:\\shares\\ltc\\ltc\\ltc-adc\\copypwd\\copypwd-exe\\copypwdsvc.exe",
    "subject.process.guid": "684DA293-948C-5A3B-0300-0010825BE168",
    "subject.process.id": "6396",
    "subject.process.name": "copypwdsvc.exe",
    "subject.process.path": "c:\\shares\\ltc\\ltc\\ltc-adc\\copypwd\\copypwd-exe\\",
    "time": "2017-12-21T11:01:32.498Z"
}
