{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4723_An_attempt_was_made_to_change_an_account_s_password",
    "importance": "low",
    "msgid": "4723",
    "object": "account",
    "object.account.domain": "someone",
    "object.account.id": "S-1-5-21-3000000076-810000008-1900000808-1079",
    "object.account.name": "chu",
    "object.property": "password",
    "reason": "An attempt was made to change an account's password",
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "acme",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "someone$",
    "subject.account.session_id": "999",
    "time": "2013-10-14T12:48:57.803Z"
}
