{
    "action": "deelevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "5517",
    "event_src.category": "AAA",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_disp",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "CRED_DISP",
    "object": "account",
    "reason": "PAM:setcred",
    "status": "success",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/bin/sudo",
    "subject.process.id": "2409",
    "subject.process.name": "sudo",
    "subject.process.path": "/usr/bin/",
    "subject.state": "disposed-credentials",
    "time": "2020-08-25T19:46:39.000Z"
}
