{
    "action": "remove",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "pc.domain.ru",
    "event_src.hostname": "pc",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_23_File_delete",
    "importance": "info",
    "msgid": "23",
    "object": "file_object",
    "object.account.domain": "domain",
    "object.account.name": "user",
    "object.fullpath": "c:\\temp\\hkcmd - copy.exe",
    "object.hash.imphash": "01E7DF883C957E178CF7A659BED81439",
    "object.hash.md5": "2F1AD2944824B6149D3E31BCB86FFE37",
    "object.hash.sha256": "D0F2505697323ECC05D72689B84F004DDD28D2810416E21C9A41E0148C9245E7",
    "object.name": "hkcmd - copy.exe",
    "object.path": "c:\\temp\\",
    "object.property": "archived",
    "object.state": "saved to disk",
    "object.type": "executable",
    "object.value": "true",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "c:\\windows\\explorer.exe",
    "subject.process.guid": "12f7ec4b-2a35-6031-be00-000000006100",
    "subject.process.id": "9748",
    "subject.process.name": "explorer.exe",
    "subject.process.path": "c:\\windows\\",
    "time": "2021-02-25T12:43:01.206Z"
}
