{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "568",
    "event_src.category": "Operating system",
    "event_src.fqdn": "x0.cockpit.lan",
    "event_src.hostname": "x0",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_avc",
    "importance": "low",
    "msgid": "USER_AVC",
    "object": "command",
    "object.value": "dbus_bind(org.freedesktop.sssd.infopipe)",
    "reason": "ALLOWED",
    "status": "success",
    "subject": "process",
    "subject.process.id": "7833",
    "time": "2016-10-03T12:27:25.000Z"
}
