{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "10435",
    "event_src.category": "Operating system",
    "event_src.hostname": "debian10siem",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_chauthtok",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts1",
    "msgid": "USER_CHAUTHTOK",
    "object": "account",
    "object.account.name": "mpuser",
    "reason": "PAM:chauthtok",
    "status": "failure",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "39",
    "subject.process.fullpath": "/usr/bin/passwd",
    "subject.process.id": "3827",
    "subject.process.name": "passwd",
    "subject.process.path": "/usr/bin/",
    "time": "2019-12-09T13:31:37.000Z"
}
