{
    "action": "modify",
    "category.generic": "Process",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.hostname": "citylights",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_25_Process_tampering",
    "importance": "info",
    "msgid": "25",
    "object": "process",
    "object.account.domain": "nt authority",
    "object.account.id": "synthetic:system@nt authority",
    "object.account.name": "system",
    "object.process.fullpath": "c:\\windows\\system32\\wbem\\wmiadap.exe",
    "object.process.guid": "77B1E971-B258-637D-3600-000000004B00",
    "object.process.id": "336",
    "object.process.name": "wmiadap.exe",
    "object.process.path": "c:\\windows\\system32\\wbem\\",
    "reason": "Image is locked for access",
    "status": "failure",
    "time": "2022-11-23T05:40:40.593Z"
}
