{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield6": "0x120196",
    "dst.fqdn": "s-ad-001.ptlab.ru",
    "dst.hostname": "s-ad-001",
    "event_src.category": "Operating system",
    "event_src.fqdn": "s-ad-001.ptlab.ru",
    "event_src.hostname": "s-ad-001",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5145_A_network_share_object_was_checked",
    "importance": "medium",
    "msgid": "5145",
    "object": "file_object",
    "object.fullpath": "\\admin$\\psexesvc.exe",
    "object.name": "psexesvc.exe",
    "object.path": "\\admin$\\",
    "object.storage.fullpath": "c:\\windows\\psexesvc.exe",
    "object.storage.id": "\\\\*\\admin$",
    "object.storage.name": "psexesvc.exe",
    "object.storage.path": "c:\\windows\\",
    "object.type": "file",
    "src.ip": "10.125.4.11",
    "src.port": 56245,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "ptlab",
    "subject.account.id": "S-1-5-21-1429952499-3518759572-2917866074-1106",
    "subject.account.name": "user",
    "subject.account.privileges": "%%1538\r\n\t\t\t\t%%1541\r\n\t\t\t\t%%4417\r\n\t\t\t\t%%4418\r\n\t\t\t\t%%4420\r\n\t\t\t\t%%4423\r\n\t\t\t\t%%4424",
    "subject.account.session_id": "285561692",
    "time": "2018-03-30T14:13:07.665Z"
}
