{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield6": "0x80",
    "dst.fqdn": "8p1x64-soft.ad2012.ru",
    "dst.hostname": "8p1x64-soft",
    "event_src.category": "Operating system",
    "event_src.fqdn": "8p1x64-soft.ad2012.ru",
    "event_src.hostname": "8p1x64-soft",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5145_A_network_share_object_was_checked",
    "importance": "medium",
    "msgid": "5145",
    "object": "file_object",
    "object.fullpath": "\\perflogs\\\\",
    "object.name": "\\",
    "object.path": "\\perflogs\\",
    "object.storage.fullpath": "c:\\perflogs\\\\",
    "object.storage.id": "\\\\*\\perflogs",
    "object.storage.name": "\\",
    "object.storage.path": "c:\\perflogs\\",
    "object.type": "file",
    "src.ip": "10.0.72.28",
    "src.port": 51027,
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "8p1x64-soft",
    "subject.account.id": "S-1-5-21-863499019-2066412432-665365160-500",
    "subject.account.name": "administrator",
    "subject.account.privileges": "%%4423",
    "subject.account.session_id": "234451378",
    "time": "2016-11-28T15:11:52.575Z"
}
