{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield6": "0x100080",
    "dst.fqdn": "exchange.oldco.ptlab",
    "dst.hostname": "exchange",
    "event_src.category": "Operating system",
    "event_src.fqdn": "exchange.oldco.ptlab",
    "event_src.hostname": "exchange",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5145_A_network_share_object_was_checked",
    "importance": "medium",
    "msgid": "5145",
    "object": "file_object",
    "object.fullpath": "\\users\\\\",
    "object.name": "\\",
    "object.path": "\\users\\",
    "object.storage.fullpath": "c:\\users\\\\",
    "object.storage.id": "\\\\*\\users",
    "object.storage.name": "\\",
    "object.storage.path": "c:\\users\\",
    "object.type": "file",
    "src.ip": "10.125.8.138",
    "src.port": 51587,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "oldco",
    "subject.account.id": "S-1-5-21-1630288417-946847275-962288545-2601",
    "subject.account.name": "test_user",
    "subject.account.privileges": "%%1541\r\n\t\t\t\t%%4423",
    "subject.account.session_id": "743200738",
    "time": "2020-08-31T07:37:53.947Z"
}
