{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield6": "0x100081",
    "dst.fqdn": "win-q4onqjg2qat.test.local",
    "dst.hostname": "win-q4onqjg2qat",
    "event_src.category": "Operating system",
    "event_src.fqdn": "win-q4onqjg2qat.test.local",
    "event_src.hostname": "win-q4onqjg2qat",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5145_A_network_share_object_was_checked",
    "importance": "medium",
    "msgid": "5145",
    "object": "file_object",
    "object.fullpath": "\\sysvol\\\\",
    "object.name": "\\",
    "object.path": "\\sysvol\\",
    "object.storage.fullpath": "c:\\windows\\sysvol\\sysvol\\\\",
    "object.storage.id": "\\\\*\\sysvol",
    "object.storage.name": "\\",
    "object.storage.path": "c:\\windows\\sysvol\\sysvol\\",
    "object.type": "file",
    "src.ip": "192.168.171.130",
    "src.port": 62118,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "test",
    "subject.account.id": "S-1-5-21-1912387110-3170147922-2054567208-1000",
    "subject.account.name": "admin",
    "subject.account.privileges": "%%1541\n\t\t\t\t%%4416\n\t\t\t\t%%4423",
    "subject.account.session_id": "277373",
    "time": "2014-09-25T14:25:34.032Z"
}
