{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "campucter.company.ru",
    "event_src.hostname": "campucter",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.domain": "company",
    "object.account.id": "S-1-5-21-1023191730-727829927-3985050192-25618",
    "object.account.name": "alalaev",
    "object.account.session_id": "27056342",
    "object.process.fullpath": "c:\\program files\\vivaldi\\application\\vivaldi.exe",
    "object.process.id": "324",
    "object.process.name": "vivaldi.exe",
    "object.process.parent.fullpath": "c:\\windows\\explorer.exe",
    "object.process.parent.id": "4552",
    "object.process.parent.name": "explorer.exe",
    "object.process.parent.path": "c:\\windows\\",
    "object.process.path": "c:\\program files\\vivaldi\\application\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "company",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-25618",
    "subject.account.name": "alalaev",
    "subject.account.privileges": "TokenElevationTypeLimited",
    "subject.account.session_id": "27056342",
    "subject.state": "on behalf of oneself",
    "time": "2017-08-10T10:53:45.823Z"
}
