{
    "action": "remove",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4699_A_scheduled_task_was_deleted",
    "importance": "info",
    "msgid": "4699",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Windows Defender\\MP Scheduled Scan",
    "object.name": "MP Scheduled Scan",
    "object.path": "\\Microsoft\\Windows Defender\\",
    "object.type": "Scheduled",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "acme",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "someone$",
    "subject.account.session_id": "999",
    "time": "2014-05-29T04:17:15.238Z"
}
