{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield4": "Client not found in Kerberos database",
    "datafield5": "0xffffffff",
    "datafield6": "-",
    "datafield8": "0x40810010",
    "datafield9": "S-1-0-0",
    "event_src.category": "AAA",
    "event_src.fqdn": "contoso-dc.contoso.com",
    "event_src.hostname": "contoso-dc",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4768_A_Kerberos_authentication_ticket_was_requested",
    "importance": "info",
    "logon_service": "krbtgt/CONTOSO.COM",
    "msgid": "4768",
    "object": "system",
    "reason": "0x6",
    "src.hostname": "localhost",
    "src.port": 0,
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "contoso2.com",
    "subject.account.id": "S-1-0-0",
    "subject.account.name": "administrator",
    "time": "2017-03-20T12:24:02.493Z"
}
