{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "9866",
    "event_src.category": "Operating system",
    "event_src.hostname": "pewpew-pc",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
    "importance": "low",
    "logon_auth_method": "local",
    "logon_service": "tty1",
    "msgid": "USER_ACCT",
    "object": "system",
    "object.process.fullpath": "/usr/libexec/gdm-session-worker",
    "object.process.id": "2158",
    "object.process.name": "gdm-session-worker",
    "object.process.path": "/usr/libexec/",
    "reason": "PAM:accounting",
    "status": "ongoing",
    "subject": "account",
    "subject.account.name": "jr",
    "subject.state": "was-authorized",
    "time": "2019-05-18T21:11:08.000Z"
}
