{
    "action": "modify",
    "category.generic": "Group",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "11671",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_ACCT",
    "object": "user_group",
    "object.name": "test111",
    "object.new_value": "test1 | <unknown>",
    "object.property": "name | password",
    "object.value": "test111 | <unknown>",
    "reason": "changing /etc/gshadow; group test111, new name: test1, new password",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/sbin/groupmod",
    "subject.process.id": "4357",
    "subject.process.name": "groupmod",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-12-22T16:55:43.000Z"
}
