{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield2": "Standard password authentication",
    "datafield4": "Pre-authentication information was invalid",
    "datafield5": "domainname",
    "datafield8": "0x40810010",
    "event_src.category": "AAA",
    "event_src.fqdn": "dc1.domainname.ru",
    "event_src.hostname": "dc1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4771_Kerberos_pre_authentication_failed",
    "importance": "info",
    "logon_service": "krbtgt",
    "logon_type": 2,
    "msgid": "4771",
    "object": "system",
    "reason": "0x18",
    "src.ip": "10.0.76.40",
    "src.port": 61495,
    "status": "failure",
    "subject": "account",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-14613",
    "subject.account.name": "username",
    "time": "2015-09-25T07:49:54.611Z"
}
