{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "434",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_start",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_START",
    "object": "account",
    "object.account.name": "root",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/bin/sudo",
    "subject.process.id": "2242",
    "subject.process.name": "sudo",
    "subject.process.path": "/usr/bin/",
    "subject.state": "started-session",
    "time": "2020-10-16T07:49:00.000Z"
}
