{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "99353893",
    "event_src.category": "Operating system",
    "event_src.ip": "10.10.193.10",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_start",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": ":22",
    "msgid": "USER_START",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/xrdp-sesman",
    "object.process.id": "2967406",
    "object.process.name": "xrdp-sesman",
    "object.process.path": "/usr/sbin/",
    "status": "ongoing",
    "subject": "account",
    "subject.account.domain": "domain",
    "subject.account.name": "userdtr",
    "subject.state": "started-session",
    "time": "2022-10-05T12:43:50.000Z"
}
