{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "434",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_start",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": "tty2",
    "msgid": "USER_START",
    "object": "system",
    "object.process.fullpath": "/usr/lib/gdm3/gdm-session-worker",
    "object.process.id": "1412",
    "object.process.name": "gdm-session-worker",
    "object.process.path": "/usr/lib/gdm3/",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "2",
    "subject.state": "started-session",
    "time": "2020-10-16T07:49:00.000Z"
}
