{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "5119",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_cmd",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts1",
    "msgid": "USER_CMD",
    "object": "command",
    "object.process.cmdline": "su",
    "object.process.cwd": "/root",
    "status": "failure",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "1000",
    "subject.account.session_id": "17",
    "time": "2019-12-09T05:30:34.000Z"
}
