{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "1755",
    "event_src.category": "Operating system",
    "event_src.hostname": "jr-virtual-machine",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_chauthtok",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_CHAUTHTOK",
    "object": "account",
    "object.account.name": "test1",
    "reason": "adding user to shadow group",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/sbin/usermod",
    "subject.process.id": "1767",
    "subject.process.name": "usermod",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-10-20T13:16:15.000Z"
}
