{
    "action": "access",
    "event_src.category": "Other",
    "event_src.fqdn": "dc-2.bankoff.stf",
    "event_src.hostname": "dc-2",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_9_Raw_access_read",
    "importance": "info",
    "msgid": "9",
    "object": "device",
    "object.name": "\\Device\\HarddiskVolume1",
    "reason": "raw access read",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "nt authority",
    "subject.account.id": "synthetic:system@nt authority",
    "subject.account.name": "system",
    "subject.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "subject.process.guid": "0CB7496C-876E-637B-3A00-000000001A00",
    "subject.process.id": "3564",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2022-11-23T23:59:56.488Z"
}
