{
    "action": "modify",
    "category.generic": "Registry Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_13_Registry_value_changed",
    "importance": "info",
    "msgid": "13",
    "object": "reg_object",
    "object.fullpath": "\\registry\\machine\\system\\controlset001\\services\\copypwdsvc\\imagepath",
    "object.name": "imagepath",
    "object.new_value": "c:\\shares\\ltc\\ltc\\ltc-adc\\copypwd\\copypwd-exe\\copypwdsvc.exe",
    "object.path": "\\registry\\machine\\system\\controlset001\\services\\copypwdsvc\\",
    "object.property": "value",
    "status": "success",
    "subject.process.fullpath": "c:\\windows\\system32\\services.exe",
    "subject.process.guid": "684DA293-FB37-5A2C-0000-00108BA80000",
    "subject.process.id": "600",
    "subject.process.name": "services.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2017-12-21T11:01:32.482Z"
}
