{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "ec1d0d90-9e3e-0002-250e-1dec3e9ed701",
    "datafield6": "Interactive",
    "datafield7": "this is either due to a bad username or authentication information, user name is correct but the password is wrong",
    "datafield9": "Negotiate",
    "dst.fqdn": "comp.domain.com",
    "dst.hostname": "comp",
    "event_src.category": "AAA",
    "event_src.fqdn": "comp.domain.com",
    "event_src.hostname": "comp",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_auth_method": "local",
    "logon_service": "Advapi",
    "logon_type": 2,
    "msgid": "4625",
    "object": "account",
    "reason": "%%2313,0xc000006a",
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "comp",
    "subject.account.id": "S-1-5-21-3612345679-1112345656-3956789019-1013",
    "subject.account.name": "serafy",
    "subject.account.session_id": "321218944",
    "subject.process.fullpath": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    "subject.process.id": "18488",
    "subject.process.name": "chrome.exe",
    "subject.process.path": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\",
    "time": "2021-08-31T21:19:03.126Z"
}
