{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Network",
    "datafield7": "this is either due to a bad username or authentication information, user name is correct but the password is wrong",
    "datafield9": "NTLM",
    "dst.fqdn": "test-dc1-w12r2.testlab.esc",
    "dst.hostname": "test-dc1-w12r2",
    "event_src.category": "AAA",
    "event_src.fqdn": "test-dc1-w12r2.testlab.esc",
    "event_src.hostname": "test-dc1-w12r2",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_service": "NtLmSsp",
    "logon_type": 3,
    "msgid": "4625",
    "object": "system",
    "reason": "%%2313,0xc000006a",
    "src.ip": "10.0.80.31",
    "src.port": 38370,
    "status": "failure",
    "subject": "account",
    "subject.account.id": "synthetic:administrator",
    "subject.account.name": "administrator",
    "time": "2018-11-18T15:29:12.020Z"
}
