{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "0B27AEBF-3840-0007-72CA-270B4038D801",
    "datafield6": "Network",
    "datafield7": "user is currently locked out, status OK",
    "datafield9": "NTLM",
    "dst.fqdn": "as3-rewx-99.domain.com",
    "dst.hostname": "as3-rewx-99",
    "event_src.category": "AAA",
    "event_src.fqdn": "as3-rewx-99.domain.com",
    "event_src.hostname": "as3-rewx-99",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_service": "NtLmSsp",
    "logon_type": 3,
    "msgid": "4625",
    "object": "system",
    "reason": "%%2307,0x0",
    "src.hostname": "desktop",
    "src.ip": "10.10.10.10",
    "src.port": 49416,
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "domain.com",
    "subject.account.id": "synthetic:user@domain.com",
    "subject.account.name": "user",
    "time": "2022-03-29T08:37:49.620Z"
}
