{
    "action": "create",
    "event_src.category": "Other",
    "event_src.fqdn": "comp-2977.energy.stf",
    "event_src.hostname": "comp-2977",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_17_Pipe_created",
    "importance": "info",
    "msgid": "17",
    "object": "resource",
    "object.name": "PSHost.133136816837047181.15648.DefaultAppDomain.rundll32",
    "object.type": "pipe",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "energy",
    "subject.account.id": "synthetic:l_murphy@energy",
    "subject.account.name": "l_murphy",
    "subject.process.fullpath": "c:\\windows\\system32\\rundll32.exe",
    "subject.process.guid": "95235a7e-1813-637e-6332-000000001b00",
    "subject.process.id": "15648",
    "subject.process.name": "rundll32.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2022-11-23T12:54:45.518Z"
}
