{
    "action": "create",
    "category.generic": "Handle",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "comp1.domainname.ru",
    "event_src.hostname": "comp1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_wmi_4661_The_handle_to_an_object_was_requested",
    "importance": "info",
    "msgid": "4661",
    "object": "handle",
    "object.name": "DC=domainname,DC=ru",
    "object.type": "SAM_DOMAIN",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "domainname",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-22263",
    "subject.account.name": "username",
    "subject.account.privileges": "%%5400",
    "subject.account.session_id": "2033313591",
    "subject.process.fullpath": "C:\\Windows\\System32\\lsass.exe",
    "subject.process.id": "500",
    "subject.process.name": "lsass.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2015-09-24T10:18:52.000Z"
}
