{
    "action": "stop",
    "category.generic": "Service",
    "category.high": "Availability Management",
    "category.low": "Control",
    "chain_id": "7441",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_service_stop",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "SERVICE_STOP",
    "object": "service",
    "object.name": "ntp",
    "status": "failure",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "4294967295",
    "subject.process.fullpath": "/usr/lib/systemd/systemd",
    "subject.process.id": "1",
    "subject.process.name": "systemd",
    "subject.process.path": "/usr/lib/systemd/",
    "time": "2019-12-09T12:28:03.000Z"
}
