{
    "action": "create",
    "category.generic": "Group",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "589",
    "event_src.category": "Operating system",
    "event_src.hostname": "centos.local",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_add_group",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "ADD_GROUP",
    "object": "user_group",
    "object.name": "test1",
    "reason": "add-group",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/sbin/useradd",
    "subject.process.id": "2362",
    "subject.process.name": "useradd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-10-16T07:52:44.000Z"
}
