{
    "action": "create",
    "category.generic": "Group",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "5488",
    "event_src.category": "Operating system",
    "event_src.hostname": "debian10siem",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_add_group",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "ADD_GROUP",
    "object": "user_group",
    "object.id": "1001",
    "object.name": "new_test_group",
    "object.state": "adding group to /etc/group",
    "reason": "adding group to /etc/group",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/sbin/groupadd",
    "subject.process.id": "1684",
    "subject.process.name": "groupadd",
    "subject.process.path": "/usr/sbin/",
    "time": "2019-12-06T07:35:42.000Z"
}
