{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "AAA",
    "event_src.fqdn": "abcd.qwer.tyui.local",
    "event_src.hostname": "abcd",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4608_Auditing_subsystem_initialized",
    "importance": "info",
    "msgid": "4608",
    "object": "process",
    "object.process.name": "lsass.exe",
    "reason": "auditing subsystem initialized",
    "status": "success",
    "time": "2017-11-17T19:10:03.151Z"
}
