{
    "action": "modify",
    "datafield4": "unhidden",
    "event_src.category": "Operating system",
    "event_src.hostname": "win10_1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4702_A_scheduled_task_was_updated",
    "importance": "info",
    "msgid": "4702",
    "object": "task",
    "object.fullpath": "\\GoogleUpdateTaskMachineCore",
    "object.name": "GoogleUpdateTaskMachineCore",
    "object.property": "command",
    "object.state": "enabled",
    "object.type": "Scheduled",
    "object.value": "C:\\Program Files (x86)\\Google\\Update\\GoogleUpdate2.exe /c",
    "object.vendor": "win10_1\\someuser",
    "reason": "Keeps your Google software up to date. If this task is disabled or stopped, your Google software will not be kept up to date, meaning security vulnerabilities that may arise cannot be fixed and features may not work. This task uninstalls itself when there is no Google software using it",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "win10_1",
    "subject.account.id": "S-1-5-21-506420898-248497907-2261400522-1000",
    "subject.account.name": "someuser",
    "subject.account.session_id": "60188526",
    "time": "2020-02-06T10:44:04.016Z"
}
