{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield6": "0x12019f",
    "dst.fqdn": "dc01-1.newco.hitb",
    "dst.hostname": "dc01-1",
    "event_src.category": "Operating system",
    "event_src.fqdn": "dc01-1.newco.hitb",
    "event_src.hostname": "dc01-1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5145_A_network_share_object_was_checked",
    "importance": "medium",
    "msgid": "5145",
    "object": "file_object",
    "object.fullpath": "\\ipc$\\lsarpc",
    "object.name": "lsarpc",
    "object.path": "\\ipc$\\",
    "object.storage.fullpath": "\\lsarpc",
    "object.storage.id": "\\\\*\\ipc$",
    "object.storage.name": "lsarpc",
    "object.storage.path": "\\",
    "object.type": "file",
    "src.ip": "172.19.61.14",
    "src.port": 50271,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "newco",
    "subject.account.id": "S-1-5-21-1028946041-3827956430-3322205331-1211",
    "subject.account.name": "srv_mssql",
    "subject.account.privileges": "%%1538\r\n\t\t\t\t%%1541\r\n\t\t\t\t%%4416\r\n\t\t\t\t%%4417\r\n\t\t\t\t%%4418\r\n\t\t\t\t%%4419\r\n\t\t\t\t%%4420\r\n\t\t\t\t%%4423\r\n\t\t\t\t%%4424",
    "subject.account.session_id": "102783475",
    "time": "2019-10-11T11:20:30.561Z"
}
