{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield3": "0x1",
    "dst.fqdn": "aa1-bc-09.domain.com",
    "dst.hostname": "aa1-bc-09",
    "event_src.category": "Operating system",
    "event_src.fqdn": "aa1-bc-09.domain.com",
    "event_src.hostname": "aa1-bc-09",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5140_A_network_share_object_was_accessed",
    "importance": "medium",
    "msgid": "5140",
    "object": "file_object",
    "object.fullpath": "\\admin$",
    "object.name": "admin$",
    "object.path": "\\",
    "object.storage.fullpath": "c:\\windows",
    "object.storage.id": "\\\\*\\ADMIN$",
    "object.storage.name": "windows",
    "object.storage.path": "c:\\",
    "object.type": "File",
    "src.ip": "10.0.48.83",
    "src.port": 50841,
    "status": "failure",
    "subject": "account",
    "subject.account.id": "S-1-5-21-1012345670-712345627-3123456782-32015",
    "subject.account.privileges": "%%4416",
    "subject.account.session_id": "7573960988",
    "time": "2021-08-09T18:43:27.728Z"
}
