{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield3": "0x1",
    "dst.fqdn": "2012r2-dc.i2.ru",
    "dst.hostname": "2012r2-dc",
    "event_src.category": "Operating system",
    "event_src.fqdn": "2012r2-dc.i2.ru",
    "event_src.hostname": "2012r2-dc",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5140_A_network_share_object_was_accessed",
    "importance": "medium",
    "msgid": "5140",
    "object": "file_object",
    "object.fullpath": "\\ipc$",
    "object.name": "ipc$",
    "object.path": "\\",
    "object.storage.id": "\\\\*\\IPC$",
    "object.type": "File",
    "src.ip": "192.168.133.130",
    "src.port": 49497,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "i2",
    "subject.account.id": "S-1-5-21-730274280-2085475123-1874798716-1603",
    "subject.account.name": "vasya",
    "subject.account.privileges": "%%4416",
    "subject.account.session_id": "9059508",
    "time": "2018-02-16T07:57:15.370Z"
}
