{
    "action": "disable",
    "datafield2": "0",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someuser.somedomain.ru",
    "event_src.hostname": "someuser",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4701_A_scheduled_task_was_disabled",
    "importance": "info",
    "msgid": "4701",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTaskNetwork",
    "object.name": "SvcRestartTaskNetwork",
    "object.path": "\\Microsoft\\Windows\\SoftwareProtectionPlatform\\",
    "object.type": "Scheduled",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "somedomain",
    "subject.account.id": "S-1-5-20",
    "subject.account.name": "someuser$",
    "subject.account.session_id": "996",
    "subject.process.guid": "12947848928736391",
    "subject.process.id": "6220",
    "subject.process.parent.id": "920",
    "time": "2022-07-22T11:09:49.434Z"
}
