{
    "action": "modify",
    "datafield2": "0",
    "datafield4": "unhidden",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someuser-nb.somedomain.ru",
    "event_src.hostname": "someuser-nb",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4702_A_scheduled_task_was_updated",
    "importance": "info",
    "msgid": "4702",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Windows\\UpdateOrchestrator\\Schedule Work",
    "object.name": "Schedule Work",
    "object.path": "\\Microsoft\\Windows\\UpdateOrchestrator\\",
    "object.property": "command",
    "object.state": "disabled",
    "object.type": "Scheduled",
    "object.value": "%systemroot%\\system32\\usoclient.exe StartWork",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "somedomain",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "someuser-nb$",
    "subject.account.session_id": "999",
    "subject.process.guid": "50384020831209407",
    "subject.process.id": "17596",
    "subject.process.parent.id": "1444",
    "time": "2022-07-22T11:06:49.346Z"
}
