{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield1": "user tried to logon outside his day of week or time of day restrictions",
    "event_src.category": "AAA",
    "event_src.fqdn": "username.domain.net",
    "event_src.hostname": "username",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4776_Account_used_for_logon",
    "importance": "low",
    "msgid": "4776",
    "object": "system",
    "reason": "0xc000006f",
    "src.hostname": "dc1-mp-01",
    "status": "failure",
    "subject": "account",
    "subject.account.name": "dzpscaner",
    "time": "2014-12-06T22:14:33.562Z"
}
