{
    "action": "modify",
    "datafield5": "-",
    "event_src.category": "Operating system",
    "event_src.fqdn": "server.corp.com",
    "event_src.hostname": "server",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4703_A_user_right_was_adjusted",
    "importance": "medium",
    "msgid": "4703",
    "object": "account",
    "object.account.domain": "corp",
    "object.account.name": "grandadmin",
    "object.account.session_id": "1999269",
    "object.property": "privileges",
    "object.value": "SeAssignPrimaryTokenPrivilege, SeIncreaseQuotaPrivilege, SeSecurityPrivilege, SeTakeOwnershipPrivilege, SeLoadDriverPrivilege, SeSystemtimePrivilege, SeBackupPrivilege, SeRestorePrivilege, SeShutdownPrivilege, SeSystemEnvironmentPrivilege, SeUndockPrivilege, SeManageVolumePrivilege",
    "reason": "Privileges assigned",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "corp",
    "subject.account.id": "s-1-5-18",
    "subject.account.name": "server$",
    "subject.account.session_id": "999",
    "subject.process.fullpath": "C:\\Windows\\System32\\svchost.exe",
    "subject.process.id": "1012",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2020-01-29T09:08:36.821Z"
}
