{
    "action": "elevate",
    "category.generic": "Process",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "datafield2": "NT Local Security Authority / Authentication Service",
    "datafield3": "LsaRegisterLogonProcess()",
    "event_src.category": "Operating system",
    "event_src.fqdn": "comp1.domainname.ru",
    "event_src.hostname": "comp1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4673_Priveleged_service_called_by_user",
    "importance": "info",
    "msgid": "4673",
    "object": "process",
    "object.account.domain": "domainname",
    "object.account.id": "S-1-5-18",
    "object.account.name": "comp1$",
    "object.process.fullpath": "c:\\windows\\system32\\lsass.exe",
    "object.process.name": "lsass.exe",
    "object.process.path": "c:\\windows\\system32\\",
    "object.property": "privilege list",
    "object.value": "SeTcbPrivilege",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "domainname",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "comp1$",
    "subject.account.session_id": "999",
    "time": "2015-07-17T19:50:49.653Z"
}
