{
    "action": "create",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_11_File_create",
    "importance": "info",
    "msgid": "11",
    "object": "file_object",
    "object.fullpath": "c:\\shares\\ltcscriptlogs\\startupscripts\\bgv38642514\\admingroup.txt",
    "object.name": "admingroup.txt",
    "object.path": "c:\\shares\\ltcscriptlogs\\startupscripts\\bgv38642514\\",
    "object.property": "creation time",
    "object.value": "2017-08-30T22:50:07.317Z",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "system",
    "subject.process.guid": "684DA293-FB31-5A2C-0000-0010EB030000",
    "subject.process.id": "4",
    "subject.process.name": "system",
    "time": "2017-12-21T10:53:23.092Z"
}
