{
    "action": "create",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "comp-3145.energy.stf",
    "event_src.hostname": "comp-3145",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_11_File_create",
    "importance": "info",
    "msgid": "11",
    "object": "file_object",
    "object.fullpath": "c:\\users\\p_lyons\\appdata\\local\\temp\\rust_mozprofiles7zots\\startupcache\\scriptcache-new.bin",
    "object.name": "scriptcache-new.bin",
    "object.path": "c:\\users\\p_lyons\\appdata\\local\\temp\\rust_mozprofiles7zots\\startupcache\\",
    "object.property": "creation time",
    "object.value": "2022-11-23T23:59:50.737Z",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "energy",
    "subject.account.id": "synthetic:p_lyons@energy",
    "subject.account.name": "p_lyons",
    "subject.process.fullpath": "c:\\program files\\mozilla firefox\\firefox.exe",
    "subject.process.guid": "CA3A6966-B3EA-637E-7125-020000003000",
    "subject.process.id": "4208",
    "subject.process.name": "firefox.exe",
    "subject.process.path": "c:\\program files\\mozilla firefox\\",
    "time": "2022-11-23T23:59:50.737Z"
}
