{
    "action": "create",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_11_File_create",
    "importance": "info",
    "msgid": "11",
    "object": "file_object",
    "object.fullpath": "c:\\shares\\ltc\\ltc\\temp\\bat\\reportcomputercollision\\test.bat",
    "object.name": "test.bat",
    "object.path": "c:\\shares\\ltc\\ltc\\temp\\bat\\reportcomputercollision\\",
    "object.property": "creation time",
    "object.value": "2017-12-21T10:55:20.261Z",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "c:\\shares\\ltc\\bin\\ltcagent.exe",
    "subject.process.guid": "684DA293-83F0-5A3B-0300-001024C40A66",
    "subject.process.id": "71280",
    "subject.process.name": "ltcagent.exe",
    "subject.process.path": "c:\\shares\\ltc\\bin\\",
    "time": "2017-12-21T10:55:20.261Z"
}
