{
    "action": "create",
    "datafield4": "unhidden",
    "event_src.category": "Operating system",
    "event_src.fqdn": "comp_4.doma.in",
    "event_src.hostname": "comp_4",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4698_A_scheduled_task_was_created",
    "importance": "info",
    "msgid": "4698",
    "object": "task",
    "object.fullpath": "\\Opera scheduled Autoupdate 1553603943",
    "object.name": "Opera scheduled Autoupdate 1553603943",
    "object.property": "command",
    "object.state": "enabled",
    "object.type": "Scheduled",
    "object.value": "C:\\Users\\user4\\AppData\\Local\\Programs\\Opera\\launcher.exe --scheduledautoupdate $(Arg0)",
    "object.vendor": "home\\user1",
    "reason": "Проверка наличия обновлений для Opera",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "home4",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-20365",
    "subject.account.name": "user4",
    "subject.account.session_id": "1824703",
    "time": "2019-03-26T12:39:07.481Z"
}
