{
    "action": "create",
    "datafield4": "unhidden",
    "event_src.category": "Operating system",
    "event_src.fqdn": "comp_9.doma.in",
    "event_src.hostname": "comp_9",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4698_A_scheduled_task_was_created",
    "importance": "info",
    "msgid": "4698",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Windows\\UpdateOrchestrator\\AC Power Install",
    "object.name": "AC Power Install",
    "object.path": "\\Microsoft\\Windows\\UpdateOrchestrator\\",
    "object.property": "command",
    "object.state": "enabled",
    "object.type": "Scheduled",
    "object.value": "%systemroot%\\system32\\usoclient.exe StartInstall",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "home9",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "user9",
    "subject.account.session_id": "999",
    "time": "2019-09-27T06:28:56.655Z"
}
