{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "00000000-0000-0000-0000-000000000000",
    "datafield8": "99C9BF6F-4A89-A173-06DF-ADAF65B99236",
    "event_src.category": "AAA",
    "event_src.fqdn": "srv-tsod-ex1.ilp.loc",
    "event_src.hostname": "srv-tsod-ex1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4648_A_logon_was_attempted_using_explicit_credentials",
    "importance": "medium",
    "msgid": "4648",
    "object": "system",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "ilp",
    "subject.account.name": "healthmailbox5fc61ff",
    "subject.process.fullpath": "c:\\program files\\microsoft\\exchange server\\v15\\bin\\msexchangehmworker.exe",
    "subject.process.id": "10412",
    "subject.process.name": "msexchangehmworker.exe",
    "subject.process.path": "c:\\program files\\microsoft\\exchange server\\v15\\bin\\",
    "time": "2016-05-26T12:54:38.848Z"
}
