{
    "action": "access",
    "datafield3": "0",
    "datafield9": "%2D%64+%2D%6E",
    "dst.ip": "10.0.208.137",
    "event_src.category": "Web server",
    "event_src.hostname": "WIN-DGE9HAU611L",
    "event_src.ip": "10.0.208.137",
    "event_src.title": "internet_information_services",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_IIS_filemonitor_resource_access",
    "importance": "info",
    "object": "resource",
    "object.fullpath": "/cgi-bin/php?%2d%64+%2d%6e",
    "object.name": "php",
    "object.path": "/cgi-bin/php",
    "object.property": "method",
    "object.state": "404",
    "object.value": "POST",
    "protocol": "HTTP/1.1",
    "reason": "Not Found",
    "src.ip": "10.0.162.100",
    "status": "failure",
    "time": "2016-09-08T04:45:08.000Z"
}
