{
    "action": "access",
    "datafield3": "0",
    "datafield9": "-",
    "dst.ip": "10.0.211.27",
    "event_src.category": "Web server",
    "event_src.hostname": "WIN-2008R2-TEMP",
    "event_src.ip": "10.0.211.27",
    "event_src.title": "internet_information_services",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_IIS_filemonitor_resource_access",
    "importance": "low",
    "object": "resource",
    "object.fullpath": "/tmp",
    "object.name": "tmp",
    "object.path": "/tmp",
    "object.process.meta": "Microsoft-WebDAV-MiniRedir/6.3.9600",
    "object.property": "method",
    "object.state": "405",
    "object.value": "PROPFIND",
    "protocol": "HTTP/1.1",
    "reason": "Method Not Allowed",
    "src.ip": "10.2.64.58",
    "status": "failure",
    "time": "2016-09-01T08:29:39.000Z"
}
