{
    "action": "access",
    "datafield3": "0",
    "datafield9": "-",
    "event_src.category": "Web server",
    "event_src.ip": "127.0.0.1",
    "event_src.title": "internet_information_services",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_IIS_filemonitor_resource_access",
    "importance": "low",
    "object": "resource",
    "object.fullpath": "/index.php",
    "object.name": "index.php",
    "object.path": "/index.php",
    "object.process.meta": "Mozilla/4.0+(compatible;+MSIE+6.0;+Windows+NT+5.2;+SV1;+.NET+CLR+1.1.4322;+.NET+CLR+2.0.50727)",
    "object.property": "method",
    "object.state": "500",
    "object.value": "GET",
    "reason": "Internal Server Error",
    "src.ip": "127.0.0.1",
    "status": "failure",
    "time": "2016-09-08T14:19:52.000Z"
}
