{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "CD74A1F6-90E1-0007-43BE-74CDE190D701",
    "datafield6": "Network",
    "datafield7": "the token supplied to the function is invalid, status OK",
    "datafield9": "NTLM",
    "dst.fqdn": "as3-rewx-99.domain.com",
    "dst.hostname": "as3-rewx-99",
    "event_src.category": "AAA",
    "event_src.fqdn": "as3-rewx-99.domain.com",
    "event_src.hostname": "as3-rewx-99",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_type": 3,
    "msgid": "4625",
    "object": "system",
    "reason": "%%2304,0x0",
    "src.ip": "10.10.52.126",
    "src.port": 35660,
    "status": "failure",
    "subject": "account",
    "time": "2021-09-05T11:18:27.967Z"
}
