{
    "action": "modify",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_21_WMI_event_consumer_to_filter_activity_detected",
    "importance": "info",
    "msgid": "21",
    "object": "link",
    "object.name": "root\\\\subscription:LogFileEventConsumer.Name=\\\"ServiceConsumer\\\"",
    "object.query": "root\\\\subscription:__EventFilter.Name=\\\"ServiceFilter\\\"",
    "object.state": "modified",
    "object.type": "consumer-filter",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "server160",
    "subject.account.id": "synthetic:administrator@server160",
    "subject.account.name": "administrator",
    "time": "2018-11-21T07:48:11.418Z"
}
