{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "2281",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "LOGIN",
    "object": "system",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.session_id": "5",
    "subject.process.id": "2640",
    "subject.state": "changed-login-id-to",
    "time": "2020-08-18T12:10:01.000Z"
}
