{
    "action": "info",
    "datafield7": "12f7ec4b-14cf-6039-6c00-000000000400",
    "event_src.category": "Other",
    "event_src.fqdn": "pc.anon.ru",
    "event_src.hostname": "pc",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_22_DNS_query",
    "importance": "info",
    "msgid": "22",
    "object": "request",
    "object.query": "92.0.10.100.in-ar.ar.",
    "object.type": "DNS",
    "reason": "DNS name does not exist",
    "status": "failure",
    "subject.process.fullpath": "c:\\windows\\sysmon64.exe",
    "subject.process.id": "5012",
    "subject.process.name": "sysmon64.exe",
    "subject.process.path": "c:\\windows\\",
    "time": "2021-02-26T17:16:23.083Z"
}
