{
    "action": "info",
    "datafield7": "8FF00B45-7DA5-5E01-0000-0010B3E00003",
    "event_src.category": "Other",
    "event_src.fqdn": "fs.naaco.pwwwb",
    "event_src.hostname": "fs",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_22_DNS_query",
    "importance": "info",
    "msgid": "22",
    "object": "request",
    "object.property": "query results",
    "object.query": "dc03-5.NaaCo.pwwwb",
    "object.type": "DNS",
    "object.value": "10.125.6.201",
    "status": "success",
    "subject.process.fullpath": "c:\\windows\\system32\\wbem\\wmiprvse.exe",
    "subject.process.id": "1240",
    "subject.process.name": "wmiprvse.exe",
    "subject.process.path": "c:\\windows\\system32\\wbem\\",
    "time": "2020-02-10T15:57:22.791Z"
}
