{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "568",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_avc",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "USER_AVC",
    "object": "command",
    "object.account.group": "0",
    "object.account.id": "0",
    "object.account.name": "root",
    "object.process.cmdline": "systemctl list-units",
    "object.value": "status",
    "reason": "denied",
    "status": "failure",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.privileges": "system_u:object_r:unlabeled_t:s0",
    "subject.process.id": "1",
    "time": "2016-10-03T12:27:25.000Z"
}
