{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "26",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_avc",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "USER_AVC",
    "object": "command",
    "object.account.group": "0",
    "object.account.id": "0",
    "object.process.cmdline": "systemctl --no-reload disable pcscd.socket pcscd.service",
    "object.value": "disable /usr/lib/systemd/system/pcscd.socket",
    "reason": "denied",
    "status": "failure",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.privileges": "system_u:system_r:invalid_t",
    "subject.process.id": "1",
    "time": "2016-10-03T12:28:05.000Z"
}
