{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "568",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_avc",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "USER_AVC",
    "object": "command",
    "object.value": "send_msg method_call(Get)",
    "reason": "denied",
    "status": "failure",
    "subject": "process",
    "subject.privileges": "system_u:system_r:apmd_t:s0",
    "subject.process.id": "4177",
    "time": "2016-10-03T12:27:25.000Z"
}
