{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "763",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_avc",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "USER_AVC",
    "object": "command",
    "object.account.group": "0",
    "object.account.id": "0",
    "object.process.cmdline": "/usr/lib/systemd/systemd-logind",
    "object.value": "start /run/systemd/system/session-4.scope",
    "reason": "denied",
    "status": "failure",
    "subject": "process",
    "subject.privileges": "system_u:system_r:systemd_logind_t:s0",
    "subject.process.id": "1",
    "time": "2015-09-18T18:49:10.000Z"
}
