{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "2656",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_avc",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "USER_AVC",
    "object": "command",
    "object.account.group": "0",
    "object.account.id": "0",
    "object.process.cmdline": "systemctl unmask tmp.mount",
    "object.value": "enable /dev/null",
    "reason": "denied",
    "status": "failure",
    "subject": "account",
    "subject.account.id": "0",
    "subject.privileges": "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023",
    "subject.process.id": "1",
    "time": "2016-10-03T12:28:00.000Z"
}
