{
    "action": "modify",
    "category.generic": "Group",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "1031",
    "event_src.category": "Operating system",
    "event_src.hostname": "centos.local",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_grp_mgmt",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "GRP_MGMT",
    "object": "user_group",
    "object.name": "test2",
    "object.state": "delete-shadow-group",
    "reason": "delete-shadow-group",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.privileges": "0",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/sbin/userdel",
    "subject.process.id": "2248",
    "subject.process.name": "userdel",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-10-16T07:52:44.000Z"
}
