{
    "action": "modify",
    "datafield1": "Severity = Informational\r\n        Host Name = Default Host\r\n        Host Version = 5.1.14393.0\r\n        Host ID = b7ccd126-180d-4869-980a-1de1e3217a1d\r\n        Host Application = powershell.exe\r\n        Engine Version = 5.1.14393.0\r\n        Runspace ID = 28e8c6d6-4b48-45a7-8396-63a658caf157\r\n        Pipeline ID = 1\r\n        Command Name = Set-StrictMode\r\n        Command Type = Cmdlet\r\n        Script Name = \r\n        Command Path = \r\n        Sequence Number = 34\r\n        User = WORKGROUP\\SYSTEM\r\n        Connected User = \r\n        Shell ID = Microsoft.PowerShell",
    "datafield10": "WORKGROUP\\SYSTEM",
    "datafield2": "CommandInvocation(Set-StrictMode): \"Set-StrictMode\"\r\nParameterBinding(Set-StrictMode): name=\"Version\"; value=\"1.0\"",
    "datafield3": "",
    "datafield4": "powershell.exe",
    "datafield6": "S-1-5-18",
    "datafield7": "b7ccd126-180d-4869-980a-1de1e3217a1d",
    "datafield8": "5.1.14393.0",
    "datafield9": "powershell.exe",
    "event_src.category": "Operating system",
    "event_src.hostname": "win-0d7rjegcaja",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_Set_Strict_Mode",
    "importance": "info",
    "msgid": "4103",
    "object": "configuration",
    "object.state": "on",
    "object.type": "strict mode",
    "object.version": "1.0",
    "status": "success",
    "time": "2020-02-17T06:15:29.772Z"
}
