{
    "action": "create",
    "category.generic": "Group",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "29208",
    "event_src.category": "Operating system",
    "event_src.hostname": "centos7full",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_add_group",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "ADD_GROUP",
    "object": "user_group",
    "object.name": "gr",
    "reason": "add-group",
    "status": "failure",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "77",
    "subject.process.fullpath": "/usr/sbin/groupadd",
    "subject.process.id": "3784",
    "subject.process.name": "groupadd",
    "subject.process.path": "/usr/sbin/",
    "time": "2019-12-09T12:49:37.000Z"
}
