{
    "action": "logout",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "9859",
    "dst.hostname": "pewpew-pc",
    "event_src.category": "Operating system",
    "event_src.hostname": "pewpew-pc",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_end",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "USER_END",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "4602",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "src.ip": "10.0.80.38",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "odmin",
    "subject.account.session_id": "65",
    "subject.state": "ended-session",
    "time": "2019-05-18T21:03:39.000Z"
}
