{
    "action": "create",
    "category.generic": "Service",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "pc.co.domain.ru",
    "event_src.hostname": "pc",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4697_A_service_was_installed_in_the_system",
    "importance": "info",
    "msgid": "4697",
    "object": "service",
    "object.account.name": "LocalSystem",
    "object.name": "SnInstAgent",
    "object.process.fullpath": "C:\\\\WINDOWS\\\\SecurityCode\\\\08_03_1406_00\\\\SnInstAgent64.exe",
    "object.process.name": "SnInstAgent64.exe",
    "object.process.path": "C:\\\\WINDOWS\\\\SecurityCode\\\\08_03_1406_00\\\\",
    "object.property": "start type",
    "object.type": "0x10",
    "object.value": "3",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "co",
    "subject.account.id": "S-1-5-21-3503238877-3003487241-1841632481-8976",
    "subject.account.name": "snuser",
    "subject.account.session_id": "2035602590",
    "time": "2018-05-07T05:27:44.816Z"
}
