{
    "action": "create",
    "category.generic": "Service",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "computername.dnssuffix.com",
    "event_src.hostname": "computername",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4697_A_service_was_installed_in_the_system",
    "importance": "info",
    "msgid": "4697",
    "object": "service",
    "object.account.name": "LocalSystem",
    "object.name": "DevicesFlowUserSvc_1157ce15",
    "object.process.fullpath": "C:\\WINDOWS\\system32\\svchost.exe -k DevicesFlow",
    "object.process.id": "3404",
    "object.process.name": "svchost.exe -k DevicesFlow",
    "object.process.parent.id": "1516",
    "object.process.path": "C:\\WINDOWS\\system32\\",
    "object.property": "start type",
    "object.type": "0xe0",
    "object.value": "3",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "domainname",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "computername$",
    "subject.account.session_id": "999",
    "time": "2022-03-01T08:35:00.407Z"
}
