{
    "action": "modify",
    "category.generic": "Group",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "1676",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_ACCT",
    "object": "user_group",
    "object.id": "1001",
    "object.name": "test1",
    "object.new_value": "test11",
    "object.property": "name",
    "object.value": "test1",
    "reason": "changing /etc/group; group test1/1001, new name: test11",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/sbin/groupmod",
    "subject.process.id": "1735",
    "subject.process.name": "groupmod",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-10-22T14:25:04.000Z"
}
