{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "1950",
    "event_src.category": "AAA",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_acq",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "msgid": "CRED_ACQ",
    "object": "system",
    "object.process.fullpath": "/usr/lib/systemd/systemd",
    "object.process.id": "2034",
    "object.process.name": "systemd",
    "object.process.path": "/usr/lib/systemd/",
    "reason": "PAM:setcred",
    "status": "ongoing",
    "subject": "account",
    "subject.account.name": "jr",
    "subject.state": "acquired-credentials",
    "time": "2020-08-25T10:56:31.000Z"
}
