{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "941",
    "event_src.category": "AAA",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_acq",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "CRED_ACQ",
    "object": "account",
    "object.account.name": "test1",
    "reason": "PAM:setcred",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/bin/su",
    "subject.process.id": "2448",
    "subject.process.name": "su",
    "subject.process.path": "/usr/bin/",
    "subject.state": "acquired-credentials",
    "time": "2020-10-16T07:54:42.000Z"
}
