{
    "action": "create",
    "event_src.category": "File service",
    "event_src.hostname": "win7x86",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4656_A_handle_to_an_object_was_requested",
    "importance": "info",
    "msgid": "4656",
    "object": "handle",
    "object.fullpath": "C:\\test\\New Text Document - Copy (2).txt",
    "object.id": "0xcf4",
    "object.name": "New Text Document - Copy (2).txt",
    "object.path": "C:\\test\\",
    "object.type": "File",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "win7x86",
    "subject.account.id": "S-1-5-21-700000004-2600000030-4100000424-500",
    "subject.account.name": "administrator",
    "subject.account.privileges": "%%1537 %%4423",
    "subject.account.session_id": "6570715",
    "subject.process.fullpath": "C:\\Windows\\explorer.exe",
    "subject.process.id": "2872",
    "subject.process.name": "explorer.exe",
    "subject.process.path": "C:\\Windows\\",
    "time": "2014-04-10T13:52:56.410Z"
}
