{
    "action": "stop",
    "category.generic": "Service",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.hostname": "centos",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_service_stop",
    "importance": "info",
    "object": "service",
    "object.name": "rsyslog",
    "status": "success",
    "subject": "account",
    "subject.account.id": "0",
    "subject.process.fullpath": "/usr/lib/systemd/systemd",
    "subject.process.name": "systemd",
    "subject.process.path": "/usr/lib/systemd/",
    "time": "2022-12-25T16:50:40.000Z"
}
