{
  "action": "login",
  "category.generic": "Access",
  "category.high": "Authentication",
  "category.low": "Remote",
  "event_src.category": "Terminal services",
  "event_src.fqdn": "pc01.example.corp",
  "event_src.host": "pc01.example.corp",
  "event_src.hostname": "pc01",
  "event_src.subsys": "Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "1149_User_authentication_succeeded",
  "importance": "info",
  "msgid": "1149",
  "object": "system",
  "src.host": "127.0.0.1",
  "src.ip": "127.0.0.1",
  "status": "success",
  "subject": "account",
  "subject.account.domain": "example",
  "subject.account.name": "admin01",
  "time": "2019-02-13T18:04:57.452Z"
}