{
    "action": "start",
    "category.generic": "Executable Module",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Other",
    "event_src.hostname": "railways",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_7_Image_loaded",
    "importance": "low",
    "msgid": "7",
    "object": "module",
    "object.process.fullpath": "c:\\program files\\common files\\siemens\\automation\\simatic oam\\bin\\s7epromapi64x.dll",
    "object.process.hash.imphash": "E7FADBACAA5156C687F6C509739116D1",
    "object.process.hash.md5": "A43FF1200337EB7B204D58C6E90EE2B0",
    "object.process.hash.sha256": "2C9F255A050AF36B965EC62476C97F900F30F557673B6212624D3389B2A6D33C",
    "object.process.meta": "Description:S7DOS Memory Card API | Product:Siemens TIA Communication® | Company:SIEMENS AG",
    "object.process.name": "s7epromapi64x.dll",
    "object.process.original_name": "s7epromapi64x.dll",
    "object.process.path": "c:\\program files\\common files\\siemens\\automation\\simatic oam\\bin\\",
    "object.property": "signature status",
    "object.value": "Valid | SIEMENS AG",
    "object.version": "0902, 0500, 0101, 0027",
    "status": "success",
    "subject": "process",
    "subject.account.domain": "railways",
    "subject.account.id": "synthetic:operator@railways",
    "subject.account.name": "operator",
    "subject.process.fullpath": "c:\\windows\\syswow64\\s7elonls64.exe",
    "subject.process.guid": "298EA5B3-788E-6377-4078-000000006100",
    "subject.process.id": "4540",
    "subject.process.name": "s7elonls64.exe",
    "subject.process.path": "c:\\windows\\syswow64\\",
    "time": "2022-11-23T23:59:55.013Z"
}
