{
    "action": "start",
    "category.generic": "Executable Module",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_7_Image_loaded",
    "importance": "low",
    "msgid": "7",
    "object": "module",
    "object.process.fullpath": "c:\\windows\\system32\\netapi32.dll",
    "object.process.hash.md5": "EEEA40F0EDB0A6E5359E539E15D0BC77",
    "object.process.hash.sha256": "BFCBF777239C29C6AC4BC5B59591308571647B7C7FDB5571903F7403DD241E8E",
    "object.process.name": "netapi32.dll",
    "object.process.path": "c:\\windows\\system32\\",
    "object.property": "signature status",
    "object.value": "Valid | Microsoft Windows",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "c:\\windows\\system32\\lsass.exe",
    "subject.process.guid": "684DA293-FB38-5A2C-0000-0010FAA90000",
    "subject.process.id": "608",
    "subject.process.name": "lsass.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2017-12-21T11:01:11.937Z"
}
