{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Batch",
    "datafield7": "this is either due to a bad username or authentication information, user name does not exist",
    "datafield9": "Negotiate",
    "dst.fqdn": "msk-dc01.corp.tnk-bp.ru",
    "dst.hostname": "msk-dc01",
    "event_src.category": "AAA",
    "event_src.fqdn": "msk-dc01.corp.tnk-bp.ru",
    "event_src.hostname": "msk-dc01",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_service": "Advapi",
    "logon_type": 4,
    "msgid": "4625",
    "object": "system",
    "reason": "%%2313,0xc0000064",
    "src.hostname": "msk-dc01",
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "corp",
    "subject.account.id": "synthetic:hpsim007@corp",
    "subject.account.name": "hpsim007",
    "subject.process.fullpath": "C:\\Windows\\System32\\svchost.exe",
    "subject.process.id": "480",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2017-08-26T23:00:15.108Z"
}
