{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "datafield6": "Interactive",
    "datafield7": "this is either due to a bad username or authentication information, user name is correct but the password is wrong",
    "datafield9": "Negotiate",
    "dst.fqdn": "win-b1t161sqfda.contoso2.com",
    "dst.hostname": "win-b1t161sqfda",
    "event_src.category": "AAA",
    "event_src.fqdn": "win-b1t161sqfda.contoso2.com",
    "event_src.hostname": "win-b1t161sqfda",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_auth_method": "local",
    "logon_service": "seclogo",
    "logon_type": 2,
    "msgid": "4625",
    "object": "account",
    "object.account.domain": "contoso.com",
    "object.account.id": "synthetic:administrator@contoso.com",
    "object.account.name": "administrator",
    "reason": "%%2313,0xc000006a",
    "src.hostname": "win-b1t161sqfda",
    "src.ip": "::1",
    "src.port": 0,
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "contoso2",
    "subject.account.id": "S-1-5-21-216805221-4090346551-3677312284-500",
    "subject.account.name": "administrator",
    "subject.account.session_id": "235810",
    "subject.process.fullpath": "C:\\Windows\\System32\\svchost.exe",
    "subject.process.id": "904",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2017-03-21T08:48:17.280Z"
}
