{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Network",
    "datafield7": "this is either due to a bad username or authentication information, user name is correct but the password is wrong",
    "datafield9": "MICROSOFT_AUTHENTICATION_PACKAGE_V1_0",
    "dst.fqdn": "ab1-cd-11.domain.com",
    "dst.hostname": "ab1-cd-11",
    "event_src.category": "AAA",
    "event_src.fqdn": "ab1-cd-11.domain.com",
    "event_src.hostname": "ab1-cd-11",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_service": "CHAP",
    "logon_type": 3,
    "msgid": "4625",
    "object": "system",
    "reason": "%%2313,0xc000006a",
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "domain",
    "subject.account.id": "synthetic:user211@domain",
    "subject.account.name": "user211",
    "subject.process.fullpath": "C:\\Windows\\System32\\svchost.exe",
    "subject.process.id": "1224",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2018-10-18T13:04:23.670Z"
}
