{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Unlock",
    "datafield7": "this is either due to a bad username or authentication information, user name is correct but the password is wrong",
    "datafield9": "Negotiate",
    "dst.fqdn": "someone.acme.com",
    "dst.hostname": "someone",
    "event_src.category": "AAA",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4625_An_account_failed_to_log_on",
    "importance": "low",
    "logon_auth_method": "local",
    "logon_service": "User32",
    "logon_type": 7,
    "msgid": "4625",
    "object": "system",
    "reason": "%%2313,0xc000006a",
    "src.hostname": "someone",
    "src.ip": "143.81.103.215",
    "src.port": 0,
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "acme",
    "subject.account.id": "synthetic:someone@acme",
    "subject.account.name": "someone",
    "subject.process.fullpath": "C:\\Windows\\System32\\winlogon.exe",
    "subject.process.id": "712",
    "subject.process.name": "winlogon.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2013-10-22T04:46:12.001Z"
}
