{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "dst.hostname": "centos6",
    "event_src.category": "Operating system",
    "event_src.hostname": "centos6",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_user_auth",
    "importance": "info",
    "logon_service": "ssh",
    "object": "system",
    "src.hostname": "test12",
    "src.ip": "192.168.56.1",
    "status": "success",
    "subject": "account",
    "subject.account.name": "ekoz",
    "time": "2022-10-28T08:48:43.000Z"
}
