{
    "action": "remove",
    "chain_id": "1803",
    "direction": "both",
    "dst.ip": "192.168.206.129",
    "dst.port": 22,
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_crypto_key_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "CRYPTO_KEY_USER",
    "object": "resource",
    "object.type": "session_key",
    "src.ip": "192.168.206.1",
    "src.port": 64963,
    "status": "success",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "4294967295",
    "subject.process.fullpath": "/usr/sbin/sshd",
    "subject.process.id": "2172",
    "subject.process.name": "sshd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-08-18T11:41:20.000Z"
}
