{
    "action": "remove",
    "chain_id": "1790",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_crypto_key_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "CRYPTO_KEY_USER",
    "object": "resource",
    "object.property": "fp",
    "object.type": "host_key",
    "object.value": "SHA256:6f:25:f2:91:2d:81:5a:c9:38:ad:81:2f:d3:39:1f:48:31:24:1a:1a:6a:b1:9d:5f:6a:c2:04:69:7a:8a:82:de",
    "status": "success",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "4294967295",
    "subject.process.fullpath": "/usr/sbin/sshd",
    "subject.process.id": "2173",
    "subject.process.name": "sshd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-08-18T11:41:17.000Z"
}
