{
    "action": "remove",
    "chain_id": "1829",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_crypto_key_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "CRYPTO_KEY_USER",
    "object": "resource",
    "object.property": "fp",
    "object.type": "host_key",
    "object.value": "SHA256:f1:3a:f8:8f:eb:cc:11:cc:f3:be:ff:18:76:27:45:c0:22:ef:86:92:ce:93:7d:2f:7c:5d:1e:72:70:a3:58:69",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/sbin/sshd",
    "subject.process.id": "2177",
    "subject.process.name": "sshd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-08-18T11:41:20.000Z"
}
