{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "639",
    "dst.ip": "192.168.137.195",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_auth",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "USER_AUTH",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "1194",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "reason": "success",
    "src.ip": "192.168.137.1",
    "status": "ongoing",
    "subject": "account",
    "subject.account.name": "root",
    "subject.state": "authenticated",
    "time": "2019-12-06T10:15:11.000Z"
}
