{
    "action": "info",
    "datafield7": "12f7ec4b-14ce-6039-5b00-000000000400",
    "event_src.category": "Other",
    "event_src.fqdn": "pc.anon.ru",
    "event_src.hostname": "pc",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_22_DNS_query",
    "importance": "info",
    "msgid": "22",
    "object": "request",
    "object.query": "ad-anon-13",
    "object.type": "DNS",
    "reason": "DNS record does not exist",
    "status": "failure",
    "subject.process.fullpath": "c:\\windows\\system32\\spoolsv.exe",
    "subject.process.id": "4516",
    "subject.process.name": "spoolsv.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2021-02-26T15:46:27.296Z"
}
