{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "522",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_ACCT",
    "object": "account",
    "object.account.name": "test1",
    "reason": "PAM:accounting",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.process.fullpath": "/usr/bin/su",
    "subject.process.id": "2598",
    "subject.process.name": "su",
    "subject.process.path": "/usr/bin/",
    "subject.state": "was-authorized",
    "time": "2020-10-16T07:50:19.000Z"
}
