{
    "action": "modify",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_wmi_4723_An_attempt_was_made_to_change_an_account_s_password",
    "importance": "low",
    "msgid": "4723",
    "object": "account",
    "object.domain": "someone",
    "object.id": "S-1-5-21-3000000076-810000008-1900000808-1079",
    "object.name": "chu",
    "object.property": "password",
    "reason": "An attempt was made to change an account's password",
    "status": "failure",
    "subject": "account",
    "subject.domain": "acme",
    "subject.id": "S-1-5-18",
    "subject.name": "someone$",
    "time": "2013-10-14T12:48:57.000Z"
}
