{
    "action": "remove",
    "chain_id": "1828",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_crypto_key_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "CRYPTO_KEY_USER",
    "object": "resource",
    "object.property": "fp",
    "object.type": "host_key",
    "object.value": "SHA256:37:12:52:28:bd:9a:00:44:b9:18:58:48:06:5d:86:89:0c:63:a0:79:e9:3b:19:0b:14:3a:e4:a4:8b:30:80:13",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/sbin/sshd",
    "subject.process.id": "2177",
    "subject.process.name": "sshd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-08-18T11:41:20.000Z"
}
