{
    "action": "remove",
    "chain_id": "5499",
    "direction": "both",
    "dst.ip": "192.168.206.131",
    "dst.port": 22,
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_crypto_key_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "CRYPTO_KEY_USER",
    "object": "resource",
    "object.type": "session_key",
    "src.ip": "192.168.206.1",
    "src.port": 53989,
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/sbin/sshd",
    "subject.process.id": "2363",
    "subject.process.name": "sshd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-08-25T19:46:39.000Z"
}
