{
    "action": "info",
    "datafield7": "12f7ec4b-18d2-6039-c803-000000000400",
    "event_src.category": "Other",
    "event_src.fqdn": "pc.anon.ru",
    "event_src.hostname": "pc",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_22_DNS_query",
    "importance": "info",
    "msgid": "22",
    "object": "request",
    "object.query": "api2.anon.com",
    "object.type": "DNS",
    "reason": "No records found for given DNS query",
    "status": "failure",
    "subject.process.fullpath": "c:\\program files\\mozilla firefox\\firefox.exe",
    "subject.process.id": "1852",
    "subject.process.name": "firefox.exe",
    "subject.process.path": "c:\\program files\\mozilla firefox\\",
    "time": "2021-02-26T15:50:53.759Z"
}
