{
    "action": "create",
    "datafield2": "0",
    "datafield4": "hidden",
    "event_src.category": "Operating system",
    "event_src.fqdn": "nb-r914vknl.somedomain.ru",
    "event_src.hostname": "nb-r914vknl",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4698_A_scheduled_task_was_created",
    "importance": "info",
    "msgid": "4698",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Windows\\RetailDemo\\CleanupOfflineContent",
    "object.name": "CleanupOfflineContent",
    "object.path": "\\Microsoft\\Windows\\RetailDemo\\",
    "object.property": "command",
    "object.state": "enabled",
    "object.type": "Scheduled",
    "object.vendor": "$(@%systemroot%\\system32\\rdxtaskfactory.dll,-100)",
    "reason": "$(@%systemRoot%\\system32\\rdxtaskfactory.dll,-101)",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "somedomain",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "nb-r914vknl$",
    "subject.account.session_id": "999",
    "subject.process.guid": "7881299347898613",
    "subject.process.id": "10996",
    "subject.process.parent.id": "1052",
    "time": "2022-07-22T11:07:13.263Z"
}
