{
    "action": "create",
    "datafield4": "unhidden",
    "event_src.category": "Operating system",
    "event_src.fqdn": "comp_10.doma.in",
    "event_src.hostname": "comp_10",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4698_A_scheduled_task_was_created",
    "importance": "info",
    "msgid": "4698",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Office\\Office Automatic Updates 2.0",
    "object.name": "Office Automatic Updates 2.0",
    "object.path": "\\Microsoft\\Office\\",
    "object.property": "command",
    "object.state": "enabled",
    "object.type": "Scheduled",
    "object.value": "C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\OfficeC2RClient.exe /frequentupdate SCHEDULEDTASK displaylevel=False",
    "object.vendor": "microsoft office",
    "reason": "This task ensures that your Microsoft Office installation can check for updates",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "home10",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "user10",
    "subject.account.session_id": "999",
    "time": "2019-09-26T00:34:18.750Z"
}
