{
    "action": "create",
    "datafield4": "unhidden",
    "event_src.category": "Operating system",
    "event_src.fqdn": "comp_5.doma.in",
    "event_src.hostname": "comp_5",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4698_A_scheduled_task_was_created",
    "importance": "info",
    "msgid": "4698",
    "object": "task",
    "object.fullpath": "\\Обновление Браузера Яндекс",
    "object.name": "Обновление Браузера Яндекс",
    "object.property": "command",
    "object.state": "enabled",
    "object.type": "Scheduled",
    "object.value": "C:\\Users\\User5\\AppData\\Local\\Yandex\\YandexBrowser\\Application\\browser.exe --background-update --noerrdialogs",
    "object.vendor": "home5\\user5",
    "reason": "Обновление Браузера Яндекс",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "home5",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-31520",
    "subject.account.name": "user5",
    "subject.account.session_id": "690090680",
    "time": "2019-03-26T12:44:48.623Z"
}
