{
    "action": "logout",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "690",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_logout",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "msgid": "USER_LOGOUT",
    "object": "system",
    "object.process.fullpath": "/usr/libexec/gdm-session-worker",
    "object.process.id": "2130",
    "object.process.name": "gdm-session-worker",
    "object.process.path": "/usr/libexec/",
    "reason": "success",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "1",
    "subject.state": "logged-out",
    "time": "2020-10-14T14:42:10.000Z"
}
