{
    "action": "logout",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "4115",
    "dst.ip": "10.1.76.35",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_logout",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "remote",
    "logon_service": "pts1",
    "msgid": "USER_LOGOUT",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "3508",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "reason": "success",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "4",
    "subject.state": "logged-out",
    "time": "2020-08-21T15:29:24.000Z"
}
