{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "99368460",
    "event_src.category": "Operating system",
    "event_src.ip": "10.10.193.10",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "LOGIN",
    "object": "system",
    "status": "ongoing",
    "subject": "account",
    "subject.account.domain": "domain",
    "subject.account.id": "1702616967",
    "subject.account.name": "userdtr",
    "subject.account.session_id": "6046",
    "subject.process.id": "2968862",
    "subject.state": "changed-login-id-to",
    "time": "2022-10-05T12:56:29.000Z"
}
