{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "1470",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "LOGIN",
    "object": "system",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "3",
    "subject.process.id": "1750",
    "subject.state": "changed-login-id-to",
    "time": "2020-08-25T10:55:34.000Z"
}
