{
    "action": "access",
    "datafield3": "0",
    "datafield9": "-",
    "dst.fqdn": "sfb.corp.ru",
    "event_src.category": "Web server",
    "event_src.hostname": "sfb",
    "event_src.ip": "1.1.5.2",
    "event_src.title": "internet_information_services",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_IIS_filemonitor_resource_access",
    "importance": "info",
    "object": "resource",
    "object.fullpath": "/abs/handler/0fe0efe.photo",
    "object.name": "0fe0efe.photo",
    "object.path": "/abs/handler/0fe0efe.photo",
    "object.process.meta": "OC/16.0.10390.20024+(Skype+for+Business)",
    "object.property": "method",
    "object.state": "200",
    "object.value": "GET",
    "protocol": "HTTP/1.1",
    "reason": "OK",
    "src.ip": "10.3.5.5",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "corp.com",
    "subject.account.id": "synthetic:user@corp.com",
    "subject.account.name": "user",
    "time": "2023-01-19T06:42:02.000Z"
}
