{
    "action": "access",
    "datafield3": "2",
    "datafield9": "-",
    "event_src.category": "Web server",
    "event_src.ip": "10.0.211.47",
    "event_src.title": "internet_information_services",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_IIS_filemonitor_resource_access",
    "importance": "low",
    "object": "resource",
    "object.fullpath": "/",
    "object.path": "/",
    "object.process.meta": "Mozilla/4.0+(compatible;+MSIE+6.0;+Windows+NT+7.0)+PTX",
    "object.property": "method",
    "object.state": "401",
    "object.value": "GET",
    "reason": "Unauthorized",
    "src.ip": "10.0.162.100",
    "status": "failure",
    "time": "2016-09-10T13:35:37.000Z"
}
