{
    "action": "bind",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_18_Pipe_connected",
    "importance": "info",
    "msgid": "18",
    "object": "resource",
    "object.name": "1a80.1d480a878f76b33-1758.1d480a87848e831",
    "object.type": "pipe",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "c:\\windows\\softwaredistribution\\download\\install\\am_delta.exe",
    "subject.process.guid": "222467B7-C169-5BF3-0000-0010411F4B03",
    "subject.process.id": "3508",
    "subject.process.name": "am_delta.exe",
    "subject.process.path": "c:\\windows\\softwaredistribution\\download\\install\\",
    "time": "2018-11-20T08:10:19.447Z"
}
