{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "2038",
    "event_src.category": "AAA",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_refr",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "CRED_REFR",
    "object": "account",
    "object.account.name": "root",
    "reason": "PAM:setcred",
    "status": "ongoing",
    "subject": "account",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/bin/sudo",
    "subject.process.id": "2274",
    "subject.process.name": "sudo",
    "subject.process.path": "/usr/bin/",
    "subject.state": "refreshed-credentials",
    "time": "2020-08-25T14:54:18.000Z"
}
