{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "113",
    "event_src.category": "AAA",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_refr",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": "tty1",
    "msgid": "CRED_REFR",
    "object": "system",
    "object.process.fullpath": "/usr/bin/login",
    "object.process.id": "677",
    "object.process.name": "login",
    "object.process.path": "/usr/bin/",
    "reason": "PAM:setcred",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "1",
    "subject.state": "refreshed-credentials",
    "time": "2020-10-23T11:28:56.000Z"
}
