{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "84e91f2e-3d1a-6388-3402-9f4502000000",
    "event_src.category": "Other",
    "event_src.fqdn": "ssidorov-nb1.somedomain.ru",
    "event_src.hostname": "ssidorov-nb1",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_1_Process_creation",
    "importance": "info",
    "msgid": "1",
    "object": "process",
    "object.account.domain": "somedomain",
    "object.account.id": "synthetic:ssidorov@somedomain",
    "object.account.name": "ssidorov",
    "object.account.privileges": "Medium",
    "object.account.session_id": "9757983284",
    "object.process.cmdline": "KAPS.exe -u",
    "object.process.cwd": "C:\\windows\\System32\\drivers\\RivetNetworks\\Killer\\",
    "object.process.fullpath": "c:\\windows\\system32\\drivers\\rivetnetworks\\killer\\kaps.exe",
    "object.process.guid": "84e91f2e-56a1-6388-f732-020000003100",
    "object.process.hash.imphash": "55B104D16E1532E92783F26A77E3C4E9",
    "object.process.hash.md5": "807031A254911C7582365D0EB84B7463",
    "object.process.hash.sha256": "5FB3FA430E94AA9066E25A0792C5AF7C84EFC0497C9D4FF110253319F1BAFD0F",
    "object.process.id": "6092",
    "object.process.meta": "Description:KillerAPS | Product:KillerAPS | Company:Rivet Networks LLC",
    "object.process.name": "kaps.exe",
    "object.process.original_name": "KAPS.exe",
    "object.process.parent.cmdline": "\"KAPS.exe\"",
    "object.process.parent.fullpath": "c:\\windows\\system32\\drivers\\rivetnetworks\\killer\\kaps.exe",
    "object.process.parent.guid": "84e91f2e-310b-635d-8d00-000000003100",
    "object.process.parent.id": "8296",
    "object.process.parent.name": "kaps.exe",
    "object.process.parent.path": "c:\\windows\\system32\\drivers\\rivetnetworks\\killer\\",
    "object.process.path": "c:\\windows\\system32\\drivers\\rivetnetworks\\killer\\",
    "object.process.version": "2.3.3314.0",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "nt authority",
    "subject.account.id": "synthetic:system@nt authority",
    "subject.account.name": "system",
    "time": "2022-12-01T07:24:17.048Z"
}
