{
    "action": "allow",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "44",
    "direction": "ingress",
    "dst.ip": "17.19.2.255",
    "dst.port": 138,
    "event_src.category": "Operating system",
    "event_src.fqdn": "mcherry.newco.hitb",
    "event_src.hostname": "mcherry",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5156_WFP_has_permitted_connection",
    "importance": "info",
    "msgid": "5156",
    "object": "connection",
    "object.process.id": "4",
    "object.process.name": "system",
    "object.property": "ALE layer",
    "object.value": "Receive/Accept",
    "protocol": "17",
    "src.ip": "17.1.6.10",
    "src.port": 138,
    "status": "success",
    "subject": "rule",
    "subject.id": "66862",
    "time": "2019-10-09T16:07:46.589Z"
}
