{
    "action": "allow",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "48",
    "direction": "egress",
    "dst.ip": "17.19.6.10",
    "dst.port": 88,
    "event_src.category": "Operating system",
    "event_src.fqdn": "exchange.newco.hitb",
    "event_src.hostname": "exchange",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5156_WFP_has_permitted_connection",
    "importance": "info",
    "msgid": "5156",
    "object": "connection",
    "object.process.fullpath": "\\device\\harddiskvolume2\\windows\\system32\\lsass.exe",
    "object.process.id": "528",
    "object.process.name": "lsass.exe",
    "object.process.path": "\\device\\harddiskvolume2\\windows\\system32\\",
    "object.property": "ALE layer",
    "object.value": "Connect",
    "protocol": "6",
    "src.ip": "17.19.6.12",
    "src.port": 38251,
    "status": "success",
    "subject": "rule",
    "subject.id": "67188",
    "time": "2019-10-07T13:34:14.317Z"
}
