{
    "action": "allow",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "48",
    "direction": "egress",
    "dst.ip": "17.19.1.10",
    "dst.port": 135,
    "event_src.category": "Operating system",
    "event_src.fqdn": "gnixon.newco.hitb",
    "event_src.hostname": "gnixon",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5156_WFP_has_permitted_connection",
    "importance": "info",
    "msgid": "5156",
    "object": "connection",
    "object.process.fullpath": "\\device\\harddiskvolume2\\windows\\system32\\svchost.exe",
    "object.process.id": "996",
    "object.process.name": "svchost.exe",
    "object.process.path": "\\device\\harddiskvolume2\\windows\\system32\\",
    "object.property": "ALE layer",
    "object.value": "Connect",
    "protocol": "6",
    "src.ip": "17.19.6.21",
    "src.port": 50051,
    "status": "success",
    "subject": "rule",
    "subject.id": "70576",
    "time": "2019-10-08T14:07:40.707Z"
}
