{
    "action": "allow",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "46",
    "direction": "ingress",
    "dst.ip": "fe00::590d:dcec:3344:936a",
    "dst.port": 49666,
    "event_src.category": "Operating system",
    "event_src.fqdn": "newco-dcprod-reserv.newco.hitb",
    "event_src.hostname": "newco-dcprod-reserv",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5156_WFP_has_permitted_connection",
    "importance": "info",
    "msgid": "5156",
    "object": "connection",
    "object.process.fullpath": "\\device\\harddiskvolume2\\windows\\system32\\lsass.exe",
    "object.process.id": "624",
    "object.process.name": "lsass.exe",
    "object.process.path": "\\device\\harddiskvolume2\\windows\\system32\\",
    "object.property": "ALE layer",
    "object.value": "Receive/Accept",
    "protocol": "6",
    "src.ip": "fe00::59cd:d0ec:3344:936a",
    "src.port": 61512,
    "status": "success",
    "subject": "rule",
    "subject.id": "65786",
    "time": "2019-10-11T02:00:11.787Z"
}
