{
    "action": "allow",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "50",
    "direction": "egress",
    "dst.ip": "fe00::e00b:0087:0a59:b32d",
    "dst.port": 445,
    "event_src.category": "Operating system",
    "event_src.fqdn": "dc02-1.priv.newco.hitb",
    "event_src.hostname": "dc02-1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5156_WFP_has_permitted_connection",
    "importance": "info",
    "msgid": "5156",
    "object": "connection",
    "object.process.id": "4",
    "object.process.name": "system",
    "object.property": "ALE layer",
    "object.value": "Connect",
    "protocol": "6",
    "src.ip": "fe00::e900:7007:5a59:b32d",
    "src.port": 62898,
    "status": "success",
    "subject": "rule",
    "subject.id": "65788",
    "time": "2019-10-12T05:17:36.730Z"
}
