{
    "action": "allow",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "48",
    "direction": "egress",
    "dst.ip": "12.19.6.10",
    "dst.port": 389,
    "event_src.category": "Operating system",
    "event_src.fqdn": "dc01-1.newco.hitb",
    "event_src.hostname": "dc01-1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5156_WFP_has_permitted_connection",
    "importance": "info",
    "msgid": "5156",
    "object": "connection",
    "object.process.fullpath": "\\device\\harddiskvolume2\\windows\\system32\\taskhostw.exe",
    "object.process.id": "6780",
    "object.process.name": "taskhostw.exe",
    "object.process.path": "\\device\\harddiskvolume2\\windows\\system32\\",
    "object.property": "ALE layer",
    "object.value": "Connect",
    "protocol": "6",
    "src.ip": "17.1.6.10",
    "src.port": 62428,
    "status": "success",
    "subject": "rule",
    "subject.id": "65789",
    "time": "2019-10-07T10:47:05.589Z"
}
