{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "679",
    "dst.ip": "192.168.137.195",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_start",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "USER_START",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "1199",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "src.ip": "192.168.137.1",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.session_id": "1",
    "subject.state": "started-session",
    "time": "2019-12-06T10:42:34.000Z"
}
