{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "1",
    "datafield8": "4.0",
    "event_src.category": "Operating system",
    "event_src.fqdn": "wec.testlab.esc",
    "event_src.hostname": "wec",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_pipeline_executed",
    "importance": "info",
    "msgid": "4103",
    "object": "command",
    "object.account.domain": "testlab",
    "object.account.id": "S-1-5-18",
    "object.account.name": "system",
    "object.fullpath": "\\\\testlab.esc\\sysvol\\testlab.esc\\Policies\\{8F6E66CF-836C-4258-8BB2-BF943EBEA445}\\Machine\\Scripts\\Startup\\pt_wmi_subscription.ps1",
    "object.name": "pt_wmi_subscription.ps1",
    "object.path": "\\\\testlab.esc\\sysvol\\testlab.esc\\Policies\\{8F6E66CF-836C-4258-8BB2-BF943EBEA445}\\Machine\\Scripts\\Startup\\",
    "object.process.cmdline": "\"Get-Date\" -Format \"yyyy.MM.dd HH:mm:ss.ms\"",
    "object.process.name": "Get-Date",
    "object.process.parent.cmdline": "-executionpolicy bypass -file pt_wmi_subscription.ps1",
    "object.process.parent.guid": "19f1fa5c-bb12-4aea-8745-5663f1c28792",
    "object.process.parent.id": "1936",
    "object.value": "CommandInvocation(Get-Date): \"Get-Date\"\r\nParameterBinding(Get-Date): name=\"Format\"; value=\"yyyy.MM.dd HH:mm:ss.ms\"",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "testlab",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "system",
    "time": "2019-03-11T16:08:50.794Z"
}
