{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield8": "5.1.19041.1023",
    "event_src.category": "Operating system",
    "event_src.fqdn": "test_w10x64-132.testlab.esc",
    "event_src.hostname": "test_w10x64-132",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_pipeline_executed",
    "importance": "info",
    "msgid": "4103",
    "object": "command",
    "object.account.domain": "test_w10x64-132",
    "object.account.id": "S-1-5-21-2418237829-468669797-1489771779-1001",
    "object.account.name": "admin",
    "object.process.cmdline": "\"Get-Command\" -ErrorAction \"Ignore\" -Name \".\\get-addefaultdomainpasswordpolicy\" | \"Get-Command\"",
    "object.process.name": "Get-Command",
    "object.process.parent.cmdline": "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe",
    "object.process.parent.guid": "c782a97f-9ca3-43ee-9c6f-010c1cec7d88",
    "object.process.parent.id": "11696",
    "object.value": "CommandInvocation(Get-Command): \"Get-Command\"\r\nParameterBinding(Get-Command): name=\"ErrorAction\"; value=\"Ignore\"\r\nParameterBinding(Get-Command): name=\"Name\"; value=\".\\get-addefaultdomainpasswordpolicy\"\r\nNonTerminatingError(Get-Command): \"The term '.\\get-addefaultdomainpasswordpolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.\"\r\nCommandInvocation(Get-Command): \"Get-Command\"",
    "reason": "The term '.\\get-addefaultdomainpasswordpolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.\"\r\nCommandInvocation(Get-Command): \"Get-Command",
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "test_w10x64-132",
    "subject.account.id": "S-1-5-21-2418237829-468669797-1489771779-1001",
    "subject.account.name": "admin",
    "time": "2021-08-13T08:32:21.082Z"
}
