{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "1",
    "datafield8": "4.0",
    "event_src.category": "Operating system",
    "event_src.fqdn": "wec.testlab.esc",
    "event_src.hostname": "wec",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_pipeline_executed",
    "importance": "info",
    "msgid": "4103",
    "object": "command",
    "object.account.id": "S-1-5-18",
    "object.account.name": "system",
    "object.fullpath": "\\\\testlab.esc\\sysvol\\testlab.esc\\Policies\\{8F6E66CF-836C-4258-8BB2-BF943EBEA445}\\Machine\\Scripts\\Startup\\pt_wmi_subscription.ps1",
    "object.name": "pt_wmi_subscription.ps1",
    "object.path": "\\\\testlab.esc\\sysvol\\testlab.esc\\Policies\\{8F6E66CF-836C-4258-8BB2-BF943EBEA445}\\Machine\\Scripts\\Startup\\",
    "object.process.cmdline": "\"Write-Output\" -InputObject \"2019.03.18 11:31:35.3135 Instrumentation started\"",
    "object.process.name": "Write-Output",
    "object.process.parent.cmdline": "-executionpolicy bypass -file pt_wmi_subscription.ps1",
    "object.process.parent.guid": "2ba8f4a2-224f-4b02-91db-f070d966b270",
    "object.process.parent.id": "2016",
    "object.value": "CommandInvocation(Write-Output): \"Write-Output\"\r\nParameterBinding(Write-Output): name=\"InputObject\"; value=\"2019.03.18 11:31:35.3135 Instrumentation started\"",
    "status": "success",
    "subject": "account",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "system",
    "time": "2019-03-18T08:31:35.032Z"
}
