{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "776",
    "datafield7": "password",
    "dst.ip": "10.1.76.35",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_auth",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "USER_AUTH",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "2996",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "reason": "failed",
    "src.ip": "192.168.206.1",
    "status": "failure",
    "subject": "account",
    "subject.account.name": "jr",
    "time": "2020-10-14T10:21:11.000Z"
}
