{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "9866",
    "dst.hostname": "pewpew-pc",
    "event_src.category": "Operating system",
    "event_src.hostname": "pewpew-pc",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_auth",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "USER_AUTH",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "4624",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "src.ip": "10.0.80.38",
    "status": "failure",
    "subject": "account",
    "subject.account.name": "somename",
    "time": "2019-05-18T21:11:08.000Z"
}
