{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "443",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_auth",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_AUTH",
    "object": "account",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1001",
    "subject.account.name": "test1",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/bin/sudo",
    "subject.process.id": "2242",
    "subject.process.name": "sudo",
    "subject.process.path": "/usr/bin/",
    "subject.state": "authenticated",
    "time": "2020-10-20T08:44:25.000Z"
}
