{
    "action": "start",
    "category.generic": "Thread",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "0x0000000077015B70",
    "event_src.category": "Other",
    "event_src.fqdn": "agent.local",
    "event_src.hostname": "agent",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_8_Create_remote_thread",
    "importance": "low",
    "msgid": "8",
    "object": "thread",
    "object.fullpath": "c:\\windows\\system32\\ntdll.dll",
    "object.id": "2612",
    "object.name": "ntdll.dll",
    "object.path": "c:\\windows\\system32\\",
    "object.process.fullpath": "c:\\windows\\sysmon.exe",
    "object.process.guid": "28D95069-1F1B-5D9B-0000-0010CA8C0100",
    "object.process.id": "1280",
    "object.process.name": "sysmon.exe",
    "object.process.path": "c:\\windows\\",
    "object.property": "start function",
    "object.value": "EtwpNotificationThread",
    "status": "success",
    "subject": "process",
    "subject.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "subject.process.guid": "28D95069-1F18-5D9B-0000-001027120100",
    "subject.process.id": "852",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2019-10-07T11:19:17.846Z"
}
