{
    "action": "modify",
    "category.generic": "Registry Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.hostname": "8p1x64-soft",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4657_Registry_value_changed",
    "importance": "info",
    "msgid": "4657",
    "object": "reg_object",
    "object.fullpath": "\\registry\\machine\\system\\controlset001\\services\\eventlog\\security\\maxsizeupper",
    "object.name": "maxsizeupper",
    "object.new_value": "25",
    "object.path": "\\registry\\machine\\system\\controlset001\\services\\eventlog\\security",
    "object.property": "value",
    "object.value": "0",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "8p1x64-soft",
    "subject.account.id": "S-1-5-21-863499019-2066412432-665365160-500",
    "subject.account.name": "administrator",
    "subject.account.session_id": "10822784",
    "subject.process.fullpath": "C:\\Windows\\System32\\svchost.exe",
    "subject.process.id": "700",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2015-12-09T13:02:18.488Z"
}
