{
    "action": "open",
    "category.generic": "Session",
    "category.high": "Network Interaction Management",
    "category.low": "Communication",
    "chain_id": "1919",
    "direction": "from-server",
    "dst.ip": "192.168.206.129",
    "dst.port": 22,
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_crypto_session",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "CRYPTO_SESSION",
    "object": "session",
    "object.property": "cipher | key_size | mac_algo | pfs",
    "object.type": "encrypted_session",
    "object.value": "aes256-ctr | 256 | hmac-sha2-256 | curve25519-sha256@libssh.org",
    "src.ip": "192.168.206.1",
    "src.port": 60541,
    "status": "success",
    "time": "2020-08-25T14:54:09.000Z"
}
