{
    "action": "enable",
    "datafield2": "0",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someuser.somedomain.ru",
    "event_src.hostname": "someuser",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4700_A_scheduled_task_was_enabled",
    "importance": "info",
    "msgid": "4700",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTaskLogon",
    "object.name": "SvcRestartTaskLogon",
    "object.path": "\\Microsoft\\Windows\\SoftwareProtectionPlatform\\",
    "object.type": "Scheduled",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "somedomain",
    "subject.account.id": "S-1-5-20",
    "subject.account.name": "someuser$",
    "subject.account.session_id": "996",
    "subject.process.guid": "12384898975269789",
    "subject.process.id": "8836",
    "subject.process.parent.id": "1076",
    "time": "2022-07-22T11:03:13.099Z"
}
