{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Network",
    "datafield9": "MICROSOFT_AUTHENTICATION_PACKAGE_V1_0",
    "dst.fqdn": "ab1-cd-11.domain.com",
    "dst.hostname": "ab1-cd-11",
    "event_src.category": "AAA",
    "event_src.fqdn": "ab1-cd-11.domain.com",
    "event_src.hostname": "ab1-cd-11",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on",
    "importance": "info",
    "logon_auth_method": "remote",
    "logon_service": "CHAP",
    "logon_type": 3,
    "msgid": "4624",
    "object": "system",
    "object.property": "session ID with ElevatedToken",
    "object.value": "0",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "domain",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-3462",
    "subject.account.name": "user211",
    "subject.account.privileges": "local administrator rights",
    "subject.account.session_id": "346470801",
    "subject.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "subject.process.id": "1224",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2018-10-18T13:05:30.336Z"
}
