{
    "action": "create",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "5664",
    "event_src.category": "Operating system",
    "event_src.hostname": "debian10siem",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_add_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "ADD_USER",
    "object": "account",
    "object.account.id": "1001",
    "object.account.name": "new_test_user",
    "reason": "adding user",
    "status": "success",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/sbin/useradd",
    "subject.process.id": "1699",
    "subject.process.name": "useradd",
    "subject.process.path": "/usr/sbin/",
    "time": "2019-12-06T07:35:43.000Z"
}
