{
    "action": "access",
    "datafield3": "0",
    "datafield6": "X-AnonResource=true;+X-AnonResource-Backend=localhost/ecp/default.flt?~3;+X-BEResource=localhost/owa/auth/logon.aspx?~3;",
    "datafield9": "-",
    "dst.ip": "81.27.243.36",
    "event_src.category": "Web server",
    "event_src.hostname": "dc1-01",
    "event_src.ip": "10.10.20.109",
    "event_src.title": "internet_information_services",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_IIS_filemonitor_resource_access",
    "importance": "info",
    "object": "resource",
    "object.fullpath": "/owa/auth/x.js",
    "object.name": "x.js",
    "object.path": "/owa/auth/x.js",
    "object.process.meta": "Mozilla/5.0+zgrab/0.x",
    "object.property": "method",
    "object.state": "404",
    "object.value": "GET",
    "protocol": "HTTP/1.1",
    "reason": "Not Found",
    "src.ip": "64.62.197.201",
    "status": "failure",
    "time": "2021-12-06T04:47:11.000Z"
}
