{
    "action": "detect",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "State",
    "direction": "ingress",
    "dst.ip": "10.7.232.59",
    "dst.port": 59500,
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection",
    "importance": "info",
    "msgid": "3",
    "object": "connection",
    "object.account.domain": "nt authority",
    "object.account.id": "synthetic:network service@nt authority",
    "object.account.name": "network service",
    "object.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "object.process.guid": "684DA293-FB45-5A2C-0000-001066120100",
    "object.process.id": "868",
    "object.process.name": "svchost.exe",
    "object.process.path": "c:\\windows\\system32\\",
    "protocol": "tcp",
    "src.fqdn": "hostname.domain.com",
    "src.hostname": "hostname",
    "src.ip": "10.4.67.69",
    "src.port": 135,
    "status": "success",
    "subject": "rule",
    "time": "2017-12-21T10:53:01.942Z"
}
