{
    "action": "remove",
    "chain_id": "5408",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_crypto_key_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "CRYPTO_KEY_USER",
    "object": "resource",
    "object.property": "fp",
    "object.type": "host_key",
    "object.value": "SHA256:71:94:b2:fc:80:71:67:43:24:d9:e8:6a:a9:3c:dc:b6:4b:29:83:ed:b7:74:2f:29:91:71:79:53:bf:7e:cb:72",
    "status": "success",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "4294967295",
    "subject.process.fullpath": "/usr/sbin/sshd",
    "subject.process.id": "1168",
    "subject.process.name": "sshd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-08-25T19:46:24.000Z"
}
