{
    "action": "create",
    "datafield2": "0",
    "datafield4": "unhidden",
    "event_src.category": "Operating system",
    "event_src.fqdn": "nb-r914vknl.somedomain.ru",
    "event_src.hostname": "nb-r914vknl",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4698_A_scheduled_task_was_created",
    "importance": "info",
    "msgid": "4698",
    "object": "task",
    "object.fullpath": "\\MicrosoftEdgeShadowStackRollbackTask",
    "object.name": "MicrosoftEdgeShadowStackRollbackTask",
    "object.property": "command",
    "object.state": "enabled",
    "object.type": "Scheduled",
    "object.value": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\103.0.1264.62\\Installer\\setup.exe --handle-crash=\"$(ProcessPath)\"",
    "reason": "This task will toggle CET settings for Edge if a compatibility issue is discovered",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "somedomain",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "nb-r914vknl$",
    "subject.account.session_id": "999",
    "subject.process.guid": "7881299347898615",
    "subject.process.id": "11076",
    "subject.process.parent.id": "11040",
    "time": "2022-07-22T11:07:04.715Z"
}
