{
    "action": "create",
    "event_src.category": "Operating system",
    "event_src.fqdn": "comp_1.doma.in",
    "event_src.hostname": "comp_1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4698_A_scheduled_task_was_created",
    "importance": "info",
    "msgid": "4698",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Configuration Manager\\Configuration Manager Health Evaluation",
    "object.name": "Configuration Manager Health Evaluation",
    "object.path": "\\Microsoft\\Configuration Manager\\",
    "object.type": "Scheduled",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "home1",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "someone$",
    "subject.account.session_id": "999",
    "time": "2014-05-28T11:40:37.423Z"
}
