{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "12965",
    "event_src.category": "Operating system",
    "event_src.ip": "192.168.137.195",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": "tty7",
    "msgid": "USER_LOGIN",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/lightdm",
    "object.process.id": "5764",
    "object.process.name": "lightdm",
    "object.process.path": "/usr/sbin/",
    "status": "success",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.session_id": "84",
    "subject.state": "logged-in",
    "time": "2019-12-10T13:20:20.000Z"
}
