{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "114",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_login",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": "tty1",
    "msgid": "USER_LOGIN",
    "object": "system",
    "object.process.fullpath": "/usr/bin/login",
    "object.process.id": "677",
    "object.process.name": "login",
    "object.process.path": "/usr/bin/",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.session_id": "1",
    "subject.state": "logged-in",
    "time": "2020-10-23T11:28:56.000Z"
}
