{
    "action": "detect",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "State",
    "direction": "egress",
    "dst.hostname": "dc01",
    "dst.ip": "10.125.14.2",
    "dst.port": 88,
    "event_src.category": "Other",
    "event_src.fqdn": "exchange.plat.form",
    "event_src.hostname": "exchange",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection",
    "importance": "info",
    "msgid": "3",
    "object": "connection",
    "object.account.domain": "nt authority",
    "object.account.id": "synthetic:system@nt authority",
    "object.account.name": "system",
    "object.process.fullpath": "c:\\windows\\system32\\lsass.exe",
    "object.process.guid": "47460EC8-7749-606D-0B00-000000003000",
    "object.process.id": "584",
    "object.process.name": "lsass.exe",
    "object.process.path": "c:\\windows\\system32\\",
    "protocol": "tcp",
    "src.fqdn": "exchange.plat.form",
    "src.hostname": "exchange",
    "src.ip": "10.125.14.3",
    "src.port": 50385,
    "status": "success",
    "subject": "rule",
    "subject.name": "-",
    "time": "2021-04-09T10:27:51.485Z"
}
