{
    "action": "detect",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "State",
    "direction": "egress",
    "dst.ip": "10.55.174.16",
    "dst.port": 443,
    "event_src.category": "Other",
    "event_src.fqdn": "win-high-03.build.domain.com",
    "event_src.hostname": "win-high-03",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection",
    "importance": "info",
    "msgid": "3",
    "object": "connection",
    "object.account.id": "S-1-5-93-2-1",
    "object.process.fullpath": "c:\\program files\\java\\jre1.8.0_151\\bin\\java.exe",
    "object.process.guid": "f09e9f94-690a-612d-0100-001020bcd43f",
    "object.process.id": "15940",
    "object.process.name": "java.exe",
    "object.process.path": "c:\\program files\\java\\jre1.8.0_151\\bin\\",
    "protocol": "tcp",
    "src.ip": "172.11.242.221",
    "src.port": 60719,
    "status": "success",
    "subject": "rule",
    "time": "2021-08-30T23:25:24.362Z"
}
