{
    "action": "detect",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "State",
    "direction": "egress",
    "dst.fqdn": "dc.dd.domain.com",
    "dst.hostname": "dc",
    "dst.ip": "10.11.22.222",
    "dst.port": 389,
    "event_src.category": "Other",
    "event_src.fqdn": "wec.aa.domain.com",
    "event_src.hostname": "wec",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection",
    "importance": "info",
    "msgid": "3",
    "object": "connection",
    "object.process.fullpath": "<unknown process>",
    "object.process.guid": "00000000-0000-0000-0000-000000000000",
    "object.process.id": "9036",
    "object.process.name": "<unknown process>",
    "protocol": "tcp",
    "src.fqdn": "wec.aa.domain.com",
    "src.hostname": "wec",
    "src.ip": "10.11.11.11",
    "src.port": 51644,
    "status": "success",
    "subject": "rule",
    "subject.name": "-",
    "time": "2021-09-07T06:17:16.326Z"
}
