{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "222467B7-BFBA-5F6D-0000-002030250500",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.rule": "psexec_run",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_1_Process_creation",
    "importance": "info",
    "msgid": "1",
    "object": "process",
    "object.account.domain": "server160",
    "object.account.id": "synthetic:administrator@server160",
    "object.account.name": "administrator",
    "object.account.privileges": "High",
    "object.account.session_id": "337200",
    "object.process.cmdline": "C:\\Users\\Administrator\\Downloads\\PSTools\\PsExec.exe  -s cmd",
    "object.process.cwd": "C:\\Users\\Administrator\\",
    "object.process.fullpath": "c:\\users\\administrator\\downloads\\pstools\\psexec.exe",
    "object.process.guid": "222467B7-BDFD-5F75-0000-00108000E404",
    "object.process.hash.sha256": "3337E3875B05E0BFBA69AB926532E3F179E8CFBF162EBB60CE58A0281437A7EF",
    "object.process.id": "5672",
    "object.process.meta": "Description:Execute processes remotely | Product:Sysinternals PsExec | Company:Sysinternals - www.sysinternals.com",
    "object.process.name": "psexec.exe",
    "object.process.original_name": "psexec.c",
    "object.process.parent.cmdline": "\"C:\\Windows\\system32\\cmd.exe\"",
    "object.process.parent.fullpath": "c:\\windows\\system32\\cmd.exe",
    "object.process.parent.guid": "222467B7-D29C-5F6D-0000-0010BC7E2F00",
    "object.process.parent.id": "3904",
    "object.process.parent.name": "cmd.exe",
    "object.process.parent.path": "c:\\windows\\system32\\",
    "object.process.path": "c:\\users\\administrator\\downloads\\pstools\\",
    "object.process.version": "2.2",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "server160",
    "subject.account.id": "synthetic:administrator@server160",
    "subject.account.name": "administrator",
    "subject.account.privileges": "High",
    "subject.account.session_id": "337200",
    "time": "2020-10-01T11:31:09.757Z"
}
