{
    "action": "remove",
    "datafield2": "0",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someuser.somedomain.ru",
    "event_src.hostname": "someuser",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4699_A_scheduled_task_was_deleted",
    "importance": "info",
    "msgid": "4699",
    "object": "task",
    "object.fullpath": "\\Microsoft\\Windows\\UpdateOrchestrator\\Universal Orchestrator Start",
    "object.name": "Universal Orchestrator Start",
    "object.path": "\\Microsoft\\Windows\\UpdateOrchestrator\\",
    "object.type": "Scheduled",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "somedomain",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "someuser$",
    "subject.account.session_id": "999",
    "subject.process.guid": "20266198323167394",
    "subject.process.id": "5952",
    "subject.process.parent.id": "912",
    "time": "2022-07-22T11:15:25.274Z"
}
