{
    "action": "access",
    "category.generic": "File System Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield1": "0x194",
    "datafield5": "0x100000",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4663_An_attempt_was_made_to_access_an_object",
    "importance": "info",
    "msgid": "4663",
    "object": "file_object",
    "object.fullpath": "c:\\windows\\rescache\\rc0013\\rescache.dir",
    "object.name": "rescache.dir",
    "object.path": "c:\\windows\\rescache\\rc0013\\",
    "object.type": "file",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "acme",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "someone$",
    "subject.account.privileges": "%%1541",
    "subject.account.session_id": "999",
    "subject.process.fullpath": "C:\\Windows\\System32\\svchost.exe",
    "subject.process.id": "3260",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "C:\\Windows\\System32\\",
    "time": "2013-11-05T09:04:29.531Z"
}
