{
    "action": "detect",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "State",
    "direction": "egress",
    "dst.fqdn": "dc8-gtr-ww-44.domain.com",
    "dst.hostname": "dc8-gtr-ww-44",
    "dst.ip": "10.11.12.32",
    "dst.port": 5061,
    "event_src.category": "Other",
    "event_src.fqdn": "dc2-wedwde-11.domain.com",
    "event_src.hostname": "dc2-wedwde-11",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection",
    "importance": "info",
    "msgid": "3",
    "object": "connection",
    "object.process.fullpath": "<unknown process>",
    "object.process.guid": "00000000-0000-0000-0000-000000000000",
    "object.process.id": "3816",
    "object.process.name": "<unknown process>",
    "protocol": "tcp",
    "src.fqdn": "dc2-wedwde-11.domain.com",
    "src.hostname": "dc2-wedwde-11",
    "src.ip": "10.11.11.11",
    "src.port": 55324,
    "status": "success",
    "subject": "rule",
    "time": "2021-09-05T04:41:43.300Z"
}
