{
    "action": "detect",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "State",
    "direction": "egress",
    "dst.fqdn": "got.data.sample.com",
    "dst.hostname": "got",
    "dst.ip": "10.115.165.22",
    "dst.port": 443,
    "event_src.category": "Other",
    "event_src.fqdn": "olenka.domain.com",
    "event_src.hostname": "olenka",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection",
    "importance": "info",
    "msgid": "3",
    "object": "connection",
    "object.account.domain": "domain",
    "object.account.id": "synthetic:olenka@domain",
    "object.account.name": "olenka",
    "object.process.fullpath": "c:\\program files (x86)\\google\\chrome\\application\\chrome.exe",
    "object.process.guid": "226cd72f-82ea-60f6-ec00-000000006800",
    "object.process.id": "10788",
    "object.process.name": "chrome.exe",
    "object.process.path": "c:\\program files (x86)\\google\\chrome\\application\\",
    "protocol": "tcp",
    "src.fqdn": "olenka.domain.com",
    "src.hostname": "olenka",
    "src.ip": "101.10.13.44",
    "src.port": 61277,
    "status": "success",
    "subject": "rule",
    "subject.name": "-",
    "time": "2021-09-03T04:14:25.043Z"
}
