{
    "action": "detect",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "State",
    "direction": "ingress",
    "dst.fqdn": "hostname.domain.com",
    "dst.hostname": "hostname",
    "dst.ip": "fe80:0:0:0:116b:fe91:1f2d:5bcd",
    "dst.port": 63307,
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_3_Network_connection",
    "importance": "info",
    "msgid": "3",
    "object": "connection",
    "object.account.domain": "nt authority",
    "object.account.id": "synthetic:network service@nt authority",
    "object.account.name": "network service",
    "object.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "object.process.guid": "684DA293-FB47-5A2C-0000-0010AD310100",
    "object.process.id": "460",
    "object.process.name": "svchost.exe",
    "object.process.path": "c:\\windows\\system32\\",
    "protocol": "udp",
    "src.ip": "ff02:0:0:0:0:0:1:3",
    "src.port": 5355,
    "status": "success",
    "subject": "rule",
    "time": "2017-12-21T10:53:01.382Z"
}
