{
    "action": "modify",
    "category.generic": "Process",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Other",
    "event_src.fqdn": "pc.anon.ru",
    "event_src.hostname": "pc",
    "event_src.rule": "-",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_25_Process_tampering",
    "importance": "info",
    "msgid": "25",
    "object": "process",
    "object.process.fullpath": "c:\\program files\\mozilla firefox\\firefox.exe",
    "object.process.guid": "12f7ec4b-9d1e-6037-043c-000000006100",
    "object.process.id": "16476",
    "object.process.name": "firefox.exe",
    "object.process.path": "c:\\program files\\mozilla firefox\\",
    "reason": "Image is replaced",
    "status": "success",
    "time": "2021-02-25T12:50:38.753Z"
}
