{
    "action": "access",
    "category.generic": "Registry Object",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "datafield1": "0x110",
    "datafield5": "0x1",
    "event_src.category": "Operating system",
    "event_src.fqdn": "computername.dnssuffix.ru",
    "event_src.hostname": "computername",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4663_An_attempt_was_made_to_access_an_object",
    "importance": "info",
    "msgid": "4663",
    "object": "reg_object",
    "object.fullpath": "\\registry\\machine\\system\\controlset001\\control\\nls\\customlocale",
    "object.path": "\\registry\\machine\\system\\controlset001\\control\\nls\\customlocale",
    "object.type": "key",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "computername.dnssuffix.ru",
    "subject.account.id": "S-1-5-21-3228627042-334194140-788599944-1000",
    "subject.account.name": "username",
    "subject.account.privileges": "%%4432\\r\\n\\t\\t\\t\\t",
    "subject.account.session_id": "251704",
    "subject.process.fullpath": "C:\\Windows\\regedit.exe",
    "subject.process.id": "2308",
    "subject.process.name": "regedit.exe",
    "subject.process.path": "C:\\Windows\\",
    "time": "2017-11-12T07:06:11.276Z"
}
