{
    "action": "modify",
    "chain_id": "320",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_role_change",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "ssh",
    "msgid": "USER_ROLE_CHANGE",
    "object": "session",
    "object.new_value": "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023",
    "object.property": "selinux_context",
    "object.type": "terminal_session",
    "object.value": "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "2",
    "subject.process.fullpath": "/usr/sbin/sshd",
    "subject.process.id": "3461",
    "subject.process.name": "sshd",
    "subject.process.path": "/usr/sbin/",
    "time": "2020-10-14T14:41:36.000Z"
}
