{
    "action": "modify",
    "chain_id": "532",
    "event_src.category": "Operating system",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_role_change",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "tty1",
    "msgid": "USER_ROLE_CHANGE",
    "object": "session",
    "object.new_value": "sysadm_u:sysadm_r:sysadm_t:s0-s0:c0.c1023",
    "object.property": "selinux_context",
    "object.type": "terminal_session",
    "object.value": "sysadm_u:sysadm_r:sysadm_t:s0-s0:c0.c1023",
    "status": "success",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "jr",
    "subject.account.privileges": "0",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/bin/login",
    "subject.process.id": "683",
    "subject.process.name": "login",
    "subject.process.path": "/usr/bin/",
    "time": "2020-10-23T11:30:24.000Z"
}
