{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "056e8011-e9bb-0001-3880-6e05bbe9d601",
    "datafield6": "NewCredentials",
    "datafield9": "Negotiate",
    "dst.fqdn": "win10x64-150.testlab.esc",
    "dst.hostname": "win10x64-150",
    "event_src.category": "AAA",
    "event_src.fqdn": "win10x64-150.testlab.esc",
    "event_src.hostname": "win10x64-150",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on",
    "importance": "info",
    "logon_service": "seclogo",
    "logon_type": 9,
    "msgid": "4624",
    "object": "account",
    "object.account.domain": "testlab.esc",
    "object.account.name": "test-admin",
    "object.property": "session ID with ElevatedToken",
    "object.value": "0",
    "src.ip": "::1",
    "src.port": 0,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "win10x64-150",
    "subject.account.id": "S-1-5-21-2418237829-468669797-1489771779-1001",
    "subject.account.name": "admin",
    "subject.account.privileges": "local administrator rights",
    "subject.account.session_id": "78437248",
    "subject.process.fullpath": "c:\\windows\\system32\\svchost.exe",
    "subject.process.id": "3872",
    "subject.process.name": "svchost.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2021-01-22T11:12:54.425Z"
}
