{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Network",
    "datafield9": "NTLM",
    "dst.fqdn": "win7-2.example.local",
    "dst.hostname": "win7-2",
    "event_src.category": "AAA",
    "event_src.fqdn": "win7-2.example.local",
    "event_src.hostname": "win7-2",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on",
    "importance": "info",
    "logon_auth_method": "remote",
    "logon_service": "NtLmSsp",
    "logon_type": 3,
    "msgid": "4624",
    "object": "system",
    "src.ip": "10.115.142.100",
    "src.port": 42386,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "win7-2",
    "subject.account.id": "S-1-5-21-1244799787-380864708-1386841475-1001",
    "subject.account.name": "admin",
    "subject.account.session_id": "310179425",
    "time": "2018-12-07T04:08:12.968Z"
}
