{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "99368503",
    "dst.ip": "10.10.193.10",
    "event_src.category": "Operating system",
    "event_src.ip": "10.10.193.10",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_start",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "USER_START",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "2968862",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "src.ip": "10.0.72.12",
    "status": "ongoing",
    "subject": "account",
    "subject.account.domain": "domain",
    "subject.account.id": "1702616967",
    "subject.account.name": "userdtr",
    "subject.account.session_id": "6046",
    "subject.state": "started-session",
    "time": "2022-10-05T12:56:29.000Z"
}
