{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "8582",
    "dst.hostname": "pewpew-pc",
    "event_src.category": "Operating system",
    "event_src.hostname": "pewpew-pc",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_start",
    "importance": "low",
    "logon_auth_method": "remote",
    "logon_service": "ssh",
    "msgid": "USER_START",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/sshd",
    "object.process.id": "19275",
    "object.process.name": "sshd",
    "object.process.path": "/usr/sbin/",
    "src.ip": "192.168.126.131",
    "status": "ongoing",
    "subject": "account",
    "subject.account.id": "1000",
    "subject.account.name": "vmuser",
    "subject.account.session_id": "111",
    "subject.state": "started-session",
    "time": "2019-05-18T12:16:59.000Z"
}
