{
    "action": "elevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "46584515",
    "event_src.category": "Operating system",
    "event_src.ip": "10.10.8.15",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_start",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "msgid": "USER_START",
    "object": "account",
    "object.account.name": "root",
    "status": "success",
    "subject": "account",
    "subject.account.id": "4294967295",
    "subject.account.name": "unset",
    "subject.process.fullpath": "/usr/bin/sudo",
    "subject.process.id": "917133",
    "subject.process.name": "sudo",
    "subject.process.path": "/usr/bin/",
    "subject.state": "started-session",
    "time": "2022-09-14T13:30:11.000Z"
}
