{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "738897170",
    "event_src.category": "Operating system",
    "event_src.hostname": "runner-f8annqmm",
    "event_src.ip": "10.20.17.90",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_user_chauthtok",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "USER_CHAUTHTOK",
    "object": "account",
    "object.account.id": "102",
    "object.account.name": "systemd-resolve",
    "reason": "change max age",
    "status": "success",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "4294967295",
    "subject.process.fullpath": "/usr/bin/chage",
    "subject.process.id": "121685",
    "subject.process.name": "chage",
    "subject.process.path": "/usr/bin/",
    "time": "2022-10-11T16:03:39.000Z"
}
