{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "computername.dnssuffix.ru",
    "event_src.hostname": "computername",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4104_Command_executed",
    "importance": "info",
    "msgid": "4104",
    "numfield1": 1,
    "numfield2": 1,
    "object": "command",
    "object.account.id": "S-1-5-21-3228627042-334194140-788599944-1000",
    "object.fullpath": "C:\\share\\scripts\\setacl.ps1",
    "object.id": "c8fa1958-fe3b-4c5f-ba5d-da66c4dfe0ec",
    "object.name": "setacl.ps1",
    "object.path": "C:\\share\\scripts\\",
    "object.process.cmdline": "$acl = Get-ACL -Path 'C:\\New folder'$Rule=new-object System.Security.AccessControl.FileSystemAccessRule \"Everyone”, “FullControl\",\"ContainerInherit\", \"None\",\"allow\"$acl.AddAccessRule($Rule)Set-Acl -Path 'C:\\New folder' -AclObject $acl",
    "object.process.id": "2232",
    "object.value": "$acl = Get-ACL -Path 'C:\\New folder'$Rule=new-object System.Security.AccessControl.FileSystemAccessRule \"Everyone”, “FullControl\",\"ContainerInherit\", \"None\",\"allow\"$acl.AddAccessRule($Rule)Set-Acl -Path 'C:\\New folder' -AclObject $acl",
    "status": "success",
    "subject": "account",
    "subject.account.id": "S-1-5-21-3228627042-334194140-788599944-1000",
    "time": "2017-08-27T19:12:01.997Z"
}
