{
    "action": "remove",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "2254",
    "event_src.category": "Operating system",
    "event_src.hostname": "debian10siem",
    "event_src.ip": "192.168.137.192",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_del_user",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "DEL_USER",
    "object": "account",
    "object.account.name": "user1",
    "reason": "deleting user not found",
    "status": "failure",
    "subject": "account",
    "subject.account.id": "0",
    "subject.account.name": "root",
    "subject.account.privileges": "0",
    "subject.account.session_id": "4",
    "subject.process.fullpath": "/usr/sbin/userdel",
    "subject.process.id": "1491",
    "subject.process.name": "userdel",
    "subject.process.path": "/usr/sbin/",
    "time": "2019-12-09T03:57:04.000Z"
}
