{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.account.domain": "server160",
    "object.account.id": "S-1-5-21-3500636268-2529342812-1271244175-1103",
    "object.account.name": "a1",
    "object.account.session_id": "16129012",
    "object.process.cmdline": "\"C:\\Windows\\system32\\RunDll32.exe\" C:\\Windows\\System32\\SHELL32.dll,RunAsNewUser_RunDLL Local\\{4ddb9f3f-700c-4bd6-9fc0-eaf85c01d25b}.00000ddc",
    "object.process.fullpath": "c:\\windows\\system32\\rundll32.exe",
    "object.process.id": "4188",
    "object.process.name": "rundll32.exe",
    "object.process.parent.fullpath": "c:\\windows\\explorer.exe",
    "object.process.parent.id": "5180",
    "object.process.parent.name": "explorer.exe",
    "object.process.parent.path": "c:\\windows\\",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "server160",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "server16$",
    "subject.account.privileges": "TokenElevationTypeLimited",
    "subject.account.session_id": "999",
    "subject.state": "on behalf",
    "time": "2020-04-29T07:13:07.266Z"
}
