{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "222467B7-3857-5E31-0000-0020691D0500",
    "event_src.category": "Other",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_1_Process_creation",
    "importance": "info",
    "msgid": "1",
    "object": "process",
    "object.account.domain": "server160",
    "object.account.id": "synthetic:administrator@server160",
    "object.account.name": "administrator",
    "object.account.privileges": "High",
    "object.account.session_id": "335209",
    "object.process.cmdline": "\"C:\\Windows\\System32\\Taskmgr.exe\" /2",
    "object.process.cwd": "C:\\Windows\\system32\\",
    "object.process.fullpath": "c:\\windows\\system32\\taskmgr.exe",
    "object.process.guid": "222467B7-E9CB-5E3C-0000-00102AE26309",
    "object.process.hash.sha256": "292106DFDFACDC0AB33E3CB580AE23F0506CB2402B9B3CA2811A0A1C2F6EBF6C",
    "object.process.id": "3496",
    "object.process.meta": "Description:Task Manager | Product:Task Manager | Company:MicrosoftÂ® WindowsÂ® Operating System",
    "object.process.name": "taskmgr.exe",
    "object.process.original_name": "Taskmgr.exe",
    "object.process.parent.cmdline": "launchtm.exe /2",
    "object.process.parent.fullpath": "c:\\windows\\system32\\launchtm.exe",
    "object.process.parent.guid": "222467B7-E9CB-5E3C-0000-001064DD6309",
    "object.process.parent.id": "5236",
    "object.process.parent.name": "launchtm.exe",
    "object.process.parent.path": "c:\\windows\\system32\\",
    "object.process.path": "c:\\windows\\system32\\",
    "object.process.version": "1, 0, 0, 1",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "server160",
    "subject.account.id": "synthetic:administrator@server160",
    "subject.account.name": "administrator",
    "subject.account.privileges": "High",
    "subject.account.session_id": "335209",
    "time": "2020-02-07T04:38:35.407Z"
}
