{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "BCCC0811-9140-5D14-0000-002029EC0700",
    "event_src.category": "Other",
    "event_src.hostname": "win1",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_1_Process_creation",
    "importance": "info",
    "msgid": "1",
    "object": "process",
    "object.account.domain": "win1",
    "object.account.id": "synthetic:apo@win1",
    "object.account.name": "apo",
    "object.account.privileges": "High",
    "object.account.session_id": "519209",
    "object.process.cmdline": "\"C:\\Users\\Public\\Documents\\svchost.exe\" C:\\Users\\Public\\Documents\\trusteddata.xml",
    "object.process.cwd": "C:\\AD\\",
    "object.process.fullpath": "c:\\users\\public\\documents\\svchost.exe",
    "object.process.guid": "BCCC0811-E716-5D15-0000-001013EA8300",
    "object.process.hash.md5": "8E1FF76DC2A1323FA8C06F5EF7561D32",
    "object.process.id": "6460",
    "object.process.meta": "Description:MSBuild.exe | Product:MicrosoftÂ® .NET Framework | Company:Microsoft Corporation",
    "object.process.name": "svchost.exe",
    "object.process.parent.cmdline": "C:\\WINDOWS\\sysnative\\rundll32.exe",
    "object.process.parent.fullpath": "c:\\windows\\system32\\rundll32.exe",
    "object.process.parent.guid": "BCCC0811-E715-5D15-0000-00103AD68300",
    "object.process.parent.id": "5900",
    "object.process.parent.name": "rundll32.exe",
    "object.process.parent.path": "c:\\windows\\system32\\",
    "object.process.path": "c:\\users\\public\\documents\\",
    "object.process.version": "4.7.2046.0 built by: NET47REL1",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "win1",
    "subject.account.id": "synthetic:apo@win1",
    "subject.account.name": "apo",
    "subject.account.privileges": "High",
    "subject.account.session_id": "519209",
    "time": "2019-06-28T10:08:22.992Z"
}
