{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "datafield6": "684DA293-3177-5A2D-0000-0020BB736F0B",
    "event_src.category": "Other",
    "event_src.fqdn": "hostname.domain.com",
    "event_src.hostname": "hostname",
    "event_src.subsys": "Microsoft-Windows-Sysmon/Operational",
    "event_src.title": "sysmon",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Sysmon_1_Process_creation",
    "importance": "info",
    "msgid": "1",
    "object": "process",
    "object.account.domain": "company",
    "object.account.id": "synthetic:synchcorp@company",
    "object.account.name": "synchcorp",
    "object.account.privileges": "High",
    "object.account.session_id": "191853499",
    "object.process.cmdline": "C:\\Windows\\system32\\cmd.exe /c C:\\Shares\\Ltc\\LTC\\TEMP\\BAT\\ReportComputerCollision\\NYG-APP38-TBS.BAT >>C:\\Shares\\Ltc\\LTC\\TEMP\\BAT\\ReportComputerCollision\\NYG-APP38-TBS.BAT.LOG 2>>&1",
    "object.process.cwd": "C:\\Shares\\Ltc\\Ltc\\Ltc-ADC\\",
    "object.process.fullpath": "c:\\windows\\system32\\cmd.exe",
    "object.process.guid": "684DA293-9292-5A3B-0300-00102EF7AD68",
    "object.process.hash.md5": "5746BD7E255DD6A8AFA06F7C42C1BA41",
    "object.process.hash.sha256": "DB06C3534964E3FC79D2763144BA53742D7FA250CA336F4A0FE724B75AAFF386",
    "object.process.id": "68096",
    "object.process.name": "cmd.exe",
    "object.process.parent.cmdline": "\"C:\\Shares\\Ltc\\Bin\\LtcAgent.EXE\" \"C:\\Shares\\Ltc\\LTC\\TEMP\\PolicyLink\\ADC - Создание.LtcAgent\" /BaseDir:\"C:\\Shares\\Ltc\\LTC\"",
    "object.process.parent.fullpath": "c:\\shares\\ltc\\bin\\ltcagent.exe",
    "object.process.parent.guid": "684DA293-83F0-5A3B-0300-001024C40A66",
    "object.process.parent.id": "71280",
    "object.process.parent.name": "ltcagent.exe",
    "object.process.parent.path": "c:\\shares\\ltc\\bin\\",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "company",
    "subject.account.id": "synthetic:synchcorp@company",
    "subject.account.name": "synchcorp",
    "subject.account.privileges": "High",
    "subject.account.session_id": "191853499",
    "time": "2017-12-21T10:53:06.883Z"
}
