{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Network",
    "datafield9": "Kerberos",
    "dst.fqdn": "someone.acme.com",
    "dst.hostname": "someone",
    "event_src.category": "AAA",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on",
    "importance": "info",
    "logon_auth_method": "remote",
    "logon_service": "Kerberos",
    "logon_type": 3,
    "msgid": "4624",
    "object": "system",
    "src.ip": "fe80::de5:f739:aaad:affc",
    "src.port": 62033,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "acme",
    "subject.account.id": "S-1-5-21-1000000030-700000027-3900000002-18209",
    "subject.account.name": "dc1-kav-01$",
    "subject.account.session_id": "132324102",
    "time": "2013-10-17T15:45:19.401Z"
}
