{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield6": "Service",
    "datafield9": "Negotiate",
    "dst.fqdn": "dc2002.msk.rn.ru",
    "dst.hostname": "dc2002",
    "event_src.category": "AAA",
    "event_src.fqdn": "dc2002.msk.rn.ru",
    "event_src.hostname": "dc2002",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on",
    "importance": "info",
    "logon_service": "Advapi",
    "logon_type": 5,
    "msgid": "4624",
    "object": "system",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "nt authority",
    "subject.account.id": "S-1-5-18",
    "subject.account.name": "system",
    "subject.account.session_id": "999",
    "subject.process.fullpath": "c:\\windows\\system32\\services.exe",
    "subject.process.id": "644",
    "subject.process.name": "services.exe",
    "subject.process.path": "c:\\windows\\system32\\",
    "time": "2017-08-30T11:40:19.603Z"
}
