{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "B277B989-E9FB-0000-A8B9-77B2FBE9D401",
    "datafield6": "Network",
    "datafield9": "NTLM",
    "dst.fqdn": "win1.ptsec.com",
    "dst.hostname": "win1",
    "event_src.category": "AAA",
    "event_src.fqdn": "win1.ptsec.com",
    "event_src.hostname": "win1",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4624_An_account_was_successfully_logged_on",
    "importance": "info",
    "logon_auth_method": "remote",
    "logon_service": "NtLmSsp",
    "logon_type": 3,
    "msgid": "4624",
    "object": "system",
    "object.property": "session ID with ElevatedToken",
    "object.value": "0",
    "src.ip": "172.16.11.212",
    "src.port": 38318,
    "status": "success",
    "subject": "account",
    "subject.account.domain": "win1",
    "subject.account.id": "S-1-5-21-506420898-248497907-2261400522-1000",
    "subject.account.name": "someuser",
    "subject.account.privileges": "local administrator rights",
    "subject.account.session_id": "1750666",
    "time": "2019-04-03T09:10:59.515Z"
}
