{
    "action": "create",
    "category.generic": "Service",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "event_src.category": "Operating system",
    "event_src.fqdn": "someone.acme.com",
    "event_src.hostname": "someone",
    "event_src.subsys": "System",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_7045_New_Windows_Service",
    "importance": "info",
    "msgid": "7045",
    "object": "service",
    "object.account.name": "localsystem",
    "object.name": "Microsoft Policy Platform Local Authority",
    "object.process.cmdline": "\"C:\\Program Files\\Microsoft Policy Platform\\policyHost.exe\" /service",
    "object.property": "start type",
    "object.type": "Slujba rejima polzovatelya",
    "object.value": "Vruchnuyu",
    "status": "success",
    "subject": "account",
    "subject.account.id": "S-1-5-18",
    "time": "2013-11-11T09:56:25.195Z"
}
