{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield4": "Client not found in Kerberos database",
    "datafield5": "0xffffffff",
    "datafield6": "-",
    "datafield8": "0x40810010",
    "datafield9": "S-1-0-0",
    "event_src.category": "AAA",
    "event_src.fqdn": "dc-marver.hunters.net",
    "event_src.hostname": "dc-marver",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4768_A_Kerberos_authentication_ticket_was_requested",
    "importance": "info",
    "logon_service": "krbtgt/hunters.net",
    "msgid": "4768",
    "object": "system",
    "reason": "0x6",
    "src.ip": "10.62.98.35",
    "src.port": 57345,
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "hunt.net",
    "subject.account.id": "S-1-0-0",
    "subject.account.name": "kolobok",
    "time": "2017-02-27T16:14:52.767Z"
}
