{
    "action": "login",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "datafield4": "Client not found in Kerberos database",
    "datafield5": "0xffffffff",
    "datafield6": "-",
    "datafield8": "0x40810010",
    "datafield9": "S-1-0-0",
    "event_src.category": "AAA",
    "event_src.fqdn": "dcmain.bababa.ru",
    "event_src.hostname": "dcmain",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4768_A_Kerberos_authentication_ticket_was_requested",
    "importance": "info",
    "logon_service": "krkrkr/BABABA.RU",
    "msgid": "4768",
    "object": "system",
    "reason": "0x6",
    "src.ip": "10.62.7.93",
    "src.port": 63042,
    "status": "failure",
    "subject": "account",
    "subject.account.contact": "aaaaaaaaaaaa@babababababab.ru",
    "subject.account.dn": "c=ru,s=babababababab,l=uuu,o=babababababab,ou=dit,cn=1c-tech,e=aaaaaaaaaaaa@babababababab.ru",
    "subject.account.domain": "babababababab.ru",
    "subject.account.id": "S-1-0-0",
    "subject.account.name": "aaaaaaaaaaaa",
    "time": "2017-03-02T23:01:03.977Z"
}
