{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "31",
    "datafield8": "5.1.18362.628",
    "event_src.category": "Operating system",
    "event_src.fqdn": "iivanov.domainname.ru",
    "event_src.hostname": "iivanov",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_pipeline_executed",
    "importance": "info",
    "msgid": "4103",
    "object": "command",
    "object.account.domain": "domainname",
    "object.account.id": "S-1-5-21-1023191730-727829927-3985050192-38786",
    "object.account.name": "iivanov",
    "object.process.cmdline": "\"Get-Help\"",
    "object.process.name": "Get-Help",
    "object.process.parent.cmdline": "powershell.exe -noexit -command set-location -literalpath 'c:\\users\\iivanov\\documents\\мои полученные файлы'",
    "object.process.parent.guid": "fe3436e6-0930-4349-80af-c856592845e2",
    "object.process.parent.id": "9788",
    "object.value": "CommandInvocation(Get-Help): \"Get-Help\"",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "domainname",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-38786",
    "subject.account.name": "iivanov",
    "time": "2020-02-28T04:09:38.145Z"
}
