{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "5",
    "datafield8": "5.1.19041.2364",
    "event_src.category": "Operating system",
    "event_src.fqdn": "test_w10x64-130.testlab.esc",
    "event_src.hostname": "test_w10x64-130",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_pipeline_executed",
    "importance": "info",
    "msgid": "4103",
    "object": "command",
    "object.account.domain": "testlab",
    "object.account.id": "S-1-5-21-1129291328-2819992169-918366777-1223",
    "object.account.name": "danil",
    "object.process.cmdline": "\"Invoke-Expression\" -Command \"(get-location).pathif (!$?) { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }\" | \"Out-String\" -Stream \"True\" -InputObject \"C:\\Users\\danil\\Documents\"",
    "object.process.name": "Invoke-Expression",
    "object.process.parent.cmdline": "c:\\windows\\system32\\wsmprovhost.exe -embedding",
    "object.process.parent.guid": "7181337f-2e6a-489d-8da6-bad92b3fc0ef",
    "object.process.parent.id": "5524",
    "object.value": "CommandInvocation(Invoke-Expression): \"Invoke-Expression\"\r\nParameterBinding(Invoke-Expression): name=\"Command\"; value=\"(get-location).path\nif (!$?) { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }\"\r\nCommandInvocation(Out-String): \"Out-String\"\r\nParameterBinding(Out-String): name=\"Stream\"; value=\"True\"\r\nParameterBinding(Out-String): name=\"InputObject\"; value=\"C:\\Users\\danil\\Documents\"",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "testlab",
    "subject.account.id": "S-1-5-21-1129291328-2819992169-918366777-1223",
    "subject.account.name": "danil",
    "time": "2023-02-16T06:39:26.024Z"
}
