{
    "action": "execute",
    "category.generic": "Command",
    "category.high": "System Management",
    "category.low": "Manipulation",
    "chain_id": "31",
    "datafield8": "5.1.14393.0",
    "event_src.category": "Operating system",
    "event_src.fqdn": "server16.server16.int",
    "event_src.hostname": "server16",
    "event_src.subsys": "Microsoft-Windows-PowerShell/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_Common_PowerShell_4103_pipeline_executed",
    "importance": "info",
    "msgid": "4103",
    "object": "command",
    "object.account.domain": "server160",
    "object.account.id": "S-1-5-21-3500636268-2529342812-1271244175-500",
    "object.account.name": "administrator",
    "object.process.cmdline": "\"Stop-Service\" -Force \"True\" -Name \"Active Directory Certificate Services\"",
    "object.process.name": "Stop-Service",
    "object.process.parent.cmdline": "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe",
    "object.process.parent.guid": "8f0ff0b6-f5ec-4d51-9070-c93bf8f0f3df",
    "object.process.parent.id": "7832",
    "object.value": "CommandInvocation(Stop-Service): \"Stop-Service\"\r\nParameterBinding(Stop-Service): name=\"Force\"; value=\"True\"\r\nParameterBinding(Stop-Service): name=\"Name\"; value=\"Active Directory Certificate Services\"\r\nTerminatingError(Stop-Service): \"Time out has expired and the operation has not been completed.\"",
    "reason": "Time out has expired and the operation has not been completed.",
    "status": "failure",
    "subject": "account",
    "subject.account.domain": "server160",
    "subject.account.id": "S-1-5-21-3500636268-2529342812-1271244175-500",
    "subject.account.name": "administrator",
    "time": "2020-09-08T06:29:19.006Z"
}
