{
    "action": "deelevate",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "chain_id": "792",
    "event_src.category": "AAA",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_disp",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_service": "pts0",
    "msgid": "CRED_DISP",
    "object": "account",
    "object.account.id": "1000",
    "object.account.name": "jr",
    "reason": "PAM:setcred",
    "status": "success",
    "subject": "account",
    "subject.account.name": "root",
    "subject.account.session_id": "1",
    "subject.process.fullpath": "/usr/bin/su",
    "subject.process.id": "2302",
    "subject.process.name": "su",
    "subject.process.path": "/usr/bin/",
    "subject.state": "disposed-credentials",
    "time": "2020-10-16T07:52:50.000Z"
}
