{
    "action": "logout",
    "category.generic": "Operating System",
    "category.high": "Access Management",
    "category.low": "Communication",
    "chain_id": "2167",
    "event_src.category": "AAA",
    "event_src.ip": "10.1.76.35",
    "event_src.subsys": "auditd",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_structured_cred_disp",
    "importance": "low",
    "labels": "node_contains_ext_ip",
    "logon_auth_method": "local",
    "logon_service": "cron",
    "msgid": "CRED_DISP",
    "object": "system",
    "object.process.fullpath": "/usr/sbin/crond",
    "object.process.id": "2489",
    "object.process.name": "crond",
    "object.process.path": "/usr/sbin/",
    "reason": "PAM:setcred",
    "status": "ongoing",
    "subject": "account",
    "subject.account.name": "root",
    "subject.account.session_id": "3",
    "subject.state": "disposed-credentials",
    "time": "2020-08-18T12:00:01.000Z"
}
