{
    "action": "start",
    "category.generic": "Service",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.hostname": "localhost",
    "event_src.title": "unix_like",
    "id": "PT_UNIX_like_auditd_syslog_service_start",
    "importance": "info",
    "object": "service",
    "object.name": "NetworkManager-dispatcher",
    "status": "success",
    "subject": "account",
    "subject.account.id": "0",
    "subject.process.fullpath": "/usr/lib/systemd/systemd",
    "subject.process.name": "systemd",
    "subject.process.path": "/usr/lib/systemd/",
    "time": "2023-04-10T11:47:10.000Z"
}
