{
    "action": "allow",
    "category.generic": "Connection",
    "category.high": "Network Interaction Management",
    "category.low": "Control",
    "datafield5": "44",
    "direction": "ingress",
    "dst.ip": "10.0.209.241",
    "dst.port": 137,
    "event_src.category": "Operating system",
    "event_src.hostname": "7x64-forensic",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_5156_WFP_has_permitted_connection",
    "importance": "info",
    "msgid": "5156",
    "object": "connection",
    "object.process.id": "4",
    "object.process.name": "system",
    "object.property": "ALE layer",
    "object.value": "Receive/Accept",
    "protocol": "17",
    "src.ip": "10.0.223.255",
    "src.port": 137,
    "status": "success",
    "subject": "rule",
    "subject.id": "65874",
    "time": "2015-12-09T08:33:03.986Z"
}
