{
    "action": "stop",
    "datafield1": "1649925",
    "event_src.category": "Operating system",
    "event_src.fqdn": "win-q00000000at.test.local",
    "event_src.hostname": "win-q00000000at",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4779_A_session_was_disconnected_from_a_Window_Station",
    "importance": "info",
    "msgid": "4779",
    "object": "session",
    "object.name": "RDP-Tcp#0",
    "src.hostname": "someone",
    "src.ip": "192.168.193.63",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "test",
    "subject.account.name": "testadmin",
    "subject.account.session_id": "1649925",
    "time": "2014-09-16T09:21:32.213Z"
}
