{
    "action": "start",
    "category.generic": "Process",
    "category.high": "Availability Management",
    "category.low": "Control",
    "event_src.category": "Operating system",
    "event_src.fqdn": "seras_victoria.rogakopyta.ru",
    "event_src.hostname": "seras_victoria",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_wmi_4688_A_new_process_has_been_created",
    "importance": "info",
    "msgid": "4688",
    "object": "process",
    "object.process.cmdline": "\"C:\\Windows\\system32\\mmc.exe\" \"C:\\Windows\\system32\\eventvwr.msc\" /s",
    "object.process.fullpath": "c:\\windows\\system32\\mmc.exe",
    "object.process.id": "10544",
    "object.process.name": "mmc.exe",
    "object.process.parent.id": "5384",
    "object.process.path": "c:\\windows\\system32\\",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "rogakopyta",
    "subject.account.id": "S-1-5-21-1023191730-727829927-3985050192-16353",
    "subject.account.name": "seras_victoria",
    "subject.account.privileges": "TokenElevationTypeLimited",
    "subject.account.session_id": "935702",
    "subject.state": "on behalf of oneself",
    "time": "2017-08-24T12:18:09.000Z"
}
